// @generated by scripts/gen-preload.ts. Do not edit by hand.

import type { HealthPingRequest, HealthPingResponse, ScriptImportRequest, ScriptImportResponse, ScriptLoadRequest, ScriptLoadResponse, ScriptParseRequest, ScriptParseResponse, ScriptSaveRequest, ScriptSaveResponse, SettingsLoadRequest, SettingsLoadResponse, SettingsSaveRequest, SettingsSaveResponse } from './channels/index.js';

/** Control surface injected alongside the per-namespace methods. */
export interface LucidAPIInfrastructure {
  ipc: {
    cancel(invocationId: string): Promise<boolean>;
    onInvocation(channel: string, cb: (invocationId: string) => void): () => void;
    onEvent(channel: string, cb: (payload: { invocationId: string; event: unknown }) => void): () => void;
  };
}

export interface LucidAPI_Health {
  ping(req: HealthPingRequest): Promise<HealthPingResponse>;
}

export interface LucidAPI_Script {
  parse(req: ScriptParseRequest): Promise<ScriptParseResponse>;
  save(req: ScriptSaveRequest): Promise<ScriptSaveResponse>;
  load(req: ScriptLoadRequest): Promise<ScriptLoadResponse>;
  import(req: ScriptImportRequest): Promise<ScriptImportResponse>;
}

export interface LucidAPI_Settings {
  load(req: SettingsLoadRequest): Promise<SettingsLoadResponse>;
  save(req: SettingsSaveRequest): Promise<SettingsSaveResponse>;
}

export interface LucidAPI extends LucidAPIInfrastructure {
  health: LucidAPI_Health;
  script: LucidAPI_Script;
  settings: LucidAPI_Settings;
}
