// @generated by scripts/gen-preload.ts. Do not edit by hand.

import type { HealthPingRequest, HealthPingResponse } from './channels/index.js';

/** Control surface injected alongside the per-namespace methods. */
export interface LucidAPIInfrastructure {
  ipc: {
    cancel(invocationId: string): Promise<boolean>;
    onInvocation(channel: string, cb: (invocationId: string) => void): () => void;
    onEvent(channel: string, cb: (payload: { invocationId: string; event: unknown }) => void): () => void;
  };
}

export interface LucidAPI_Health {
  ping(req: HealthPingRequest): Promise<HealthPingResponse>;
}

export interface LucidAPI extends LucidAPIInfrastructure {
  health: LucidAPI_Health;
}
