/**
 * Preset parameter definitions, defaults, name rosters, category hints,
 * aspect-ratio mappings, and ID/description builders. Pure data + helpers.
 */
import type { PresetCategory, PresetParamDefinition, PresetParamMap } from './core.js';

export const PRESET_NAME_LIBRARY = {
  camera: [
    'zoom-in',
    'zoom-out',
    'pan-left',
    'pan-right',
    'tilt-up',
    'tilt-down',
    'dolly-in',
    'dolly-out',
    'truck-left',
    'truck-right',
    'orbit-cw',
    'orbit-ccw',
    'crane-up',
    'crane-down',
    'handheld-shake',
    'steadicam-follow',
    'static-hold',
    'subtle-drift',
    'push-in',
    'pull-out',
    'lateral-slide-left',
    'lateral-slide-right',
    'arc-left',
    'arc-right',
    'whip-pan',
    'snap-zoom',
    'parallax-reveal',
    'rack-focus',
    'handheld-run',
    'fpv-glide',
    'spiral-rise',
    'bullet-time',
  ],
  lens: [
    'ultra-wide-14mm',
    'wide-24mm',
    'normal-50mm',
    'portrait-85mm',
    'telephoto-135mm',
    'long-telephoto-200mm',
    'macro',
    'fisheye',
    'tilt-shift',
    'anamorphic',
    'vintage-soft',
    'pinhole',
  ],
  look: [
    'cinematic-realism',
    'anime-cel',
    'watercolor-ink',
    'oil-paint',
    'claymation',
    'pixel-art',
    'comic-book',
    'noir-film',
    'sci-fi-neon',
    'fantasy-epic',
    'documentary-gritty',
    'pastel-dream',
    'gothic-baroque',
    'minimal-clean',
    'retro-80s',
    'surreal-dali-esque',
    'teal-orange',
    'monochrome-cool',
    'monochrome-warm',
    'complementary-pop',
    'analogous-serene',
    'triadic-vibrant',
    'pastel-soft',
    'earth-tones',
    'neon-synthwave',
    'bleach-bypass',
    'sepia-vintage',
    'high-contrast-bw',
    'smooth-polished',
    'matte-flat',
    'grainy-film',
    'rough-grit',
    'glossy-wet',
    'velvet-soft',
    'metallic-brushed',
    'paper-fiber',
    'ceramic-glaze',
    'glass-crisp',
    'concrete-porous',
    'fabric-weave',
    'wes-anderson-pastel',
    'wong-karwai-neon',
    'kubrick-symmetry',
    'shinkai-luminous',
    'kodak-portra-400',
    'cinestill-800t',
    'fujifilm-eterna',
    'ilford-hp5',
    'french-new-wave',
    'y2k-chrome',
    'vaporwave',
    'brutalist-concrete',
    'stop-motion-clay',
    'cross-stitch',
    'rotoscope',
    'needle-felt',
  ],
  scene: [
    'golden-hour',
    'blue-hour',
    'high-key',
    'low-key',
    'rim-light',
    'silhouette',
    'split-lighting',
    'butterfly-lighting',
    'rembrandt-lighting',
    'volumetric-godrays',
    'neon-noir',
    'candlelit',
    'moonlit',
    'overcast-soft',
    'fog-light',
    'fog-heavy',
    'rain-light',
    'rain-heavy',
    'snow-gentle',
    'snow-blizzard',
    'dust-particles',
    'smoke',
    'fire-embers',
    'underwater',
    'wind-leaves',
    'fireflies',
    'sandstorm',
    'aurora',
  ],
  composition: [
    'rule-of-thirds',
    'center-frame',
    'golden-ratio',
    'leading-lines',
    'dutch-angle',
    'negative-space',
    'symmetrical',
    'frame-within-frame',
    'over-the-shoulder',
    'extreme-close-up',
  ],
  emotion: [
    'neutral',
    'hopeful',
    'tense',
    'awe',
    'melancholic',
    'euphoric',
    'ominous',
    'intimate',
    'triumphant',
    'playful',
    'reflective',
    'urgent',
  ],
  flow: [
    'linger',
    'measured',
    'conversational',
    'energetic',
    'frantic',
    'rhythmic-pulse',
    'stop-and-breathe',
    'acceleration-ramp',
    'deceleration-ramp',
    'montage-beat',
    'hard-cut',
    'match-cut',
    'jump-cut',
    'crossfade',
    'dip-to-black',
    'dip-to-white',
    'wipe-left',
    'wipe-right',
    'whip-pan-transition',
    'morph',
    'glitch-cut',
    'film-burn',
    'luma-fade',
    'iris-close',
  ],
  technical: [
    'cinematic-scope-239',
    'standard-wide-169',
    'academy-43',
    'vertical-mobile-916',
    'square-11',
    'imax-143',
    'ultra-wide-219',
    'draft',
    'standard',
    'high-fidelity',
    'max-detail',
    'turbo-preview',
  ],
} as const satisfies Record<PresetCategory, readonly string[]>;

export const CATEGORY_PROMPT_HINT: Record<PresetCategory, string> = {
  camera: 'camera movement, shot trajectory, and kinetic dynamics',
  lens: 'optical rendering, focal behavior, and depth cues',
  look: 'art-direction language, color palette, and surface texture',
  scene: 'lighting setup, weather, atmosphere, and ambient conditions',
  composition: 'subject placement, geometry, and framing balance',
  emotion: 'emotional tone, expressive body language, and atmosphere',
  flow: 'rhythm, cuts, transitions, and narrative cadence',
  technical: 'render quality, frame ratio, and output configuration',
};

export const INTENSITY_PARAM: PresetParamDefinition = {
  key: 'intensity', label: 'Intensity', type: 'number', min: 0, max: 100, defaultValue: 100,
};

export const CATEGORY_PARAM_DEFS: Record<PresetCategory, PresetParamDefinition[]> = {
  camera: [
    { key: 'speed', label: 'Speed', type: 'enum', options: ['slow', 'medium', 'fast'], defaultValue: 'medium' },
    INTENSITY_PARAM,
    { key: 'amplitude', label: 'Amplitude', type: 'number', min: 0, max: 100, defaultValue: 40 },
  ],
  lens: [
    { key: 'focalLengthMm', label: 'Focal Length', type: 'number', min: 8, max: 400, defaultValue: 50 },
    { key: 'distortion', label: 'Distortion', type: 'number', min: 0, max: 100, defaultValue: 15 },
    INTENSITY_PARAM,
  ],
  look: [
    { key: 'stylization', label: 'Stylization', type: 'number', min: 0, max: 100, defaultValue: 65 },
    { key: 'saturation', label: 'Saturation', type: 'number', min: 0, max: 100, defaultValue: 55 },
    { key: 'temperature', label: 'Temperature', type: 'number', min: -100, max: 100, defaultValue: 0 },
    { key: 'detail', label: 'Detail', type: 'number', min: 0, max: 100, defaultValue: 60 },
    INTENSITY_PARAM,
  ],
  scene: [
    { key: 'lightIntensity', label: 'Light Intensity', type: 'number', min: 0, max: 100, defaultValue: 70 },
    { key: 'contrast', label: 'Contrast', type: 'number', min: 0, max: 100, defaultValue: 45 },
    { key: 'density', label: 'Density', type: 'number', min: 0, max: 100, defaultValue: 45 },
    INTENSITY_PARAM,
  ],
  composition: [
    { key: 'balance', label: 'Balance', type: 'number', min: 0, max: 100, defaultValue: 50 },
    { key: 'bias', label: 'Subject Bias', type: 'enum', options: ['left', 'center', 'right'], defaultValue: 'center' },
    INTENSITY_PARAM,
  ],
  emotion: [
    { key: 'emotionIntensity', label: 'Emotion Intensity', type: 'number', min: 0, max: 100, defaultValue: 50 },
    { key: 'stability', label: 'Stability', type: 'number', min: 0, max: 100, defaultValue: 60 },
    INTENSITY_PARAM,
  ],
  flow: [
    { key: 'tempo', label: 'Tempo', type: 'number', min: 1, max: 10, defaultValue: 5 },
    { key: 'durationMs', label: 'Duration', type: 'number', min: 100, max: 5000, defaultValue: 900 },
    { key: 'softness', label: 'Softness', type: 'number', min: 0, max: 100, defaultValue: 40 },
    INTENSITY_PARAM,
  ],
  technical: [
    {
      key: 'ratio',
      label: 'Ratio',
      type: 'enum',
      options: ['2.39:1', '16:9', '4:3', '9:16', '1:1', '1.43:1', '21:9'],
      defaultValue: '16:9',
    },
    { key: 'quality', label: 'Quality', type: 'enum', options: ['low', 'medium', 'high', 'ultra'], defaultValue: 'medium' },
    { key: 'steps', label: 'Steps', type: 'number', min: 5, max: 80, defaultValue: 20 },
    { key: 'cfg', label: 'CFG', type: 'number', min: 1, max: 20, defaultValue: 7 },
    INTENSITY_PARAM,
  ],
};

export const CATEGORY_DEFAULTS: Record<PresetCategory, PresetParamMap> = {
  camera: { speed: 'medium', intensity: 100, amplitude: 40 },
  lens: { focalLengthMm: 50, distortion: 15, intensity: 100 },
  look: { stylization: 65, saturation: 55, temperature: 0, detail: 60, intensity: 100 },
  scene: { lightIntensity: 70, contrast: 45, density: 45, intensity: 100 },
  composition: { balance: 50, bias: 'center', intensity: 100 },
  emotion: { emotionIntensity: 50, stability: 60, intensity: 100 },
  flow: { tempo: 5, durationMs: 900, softness: 40, intensity: 100 },
  technical: { ratio: '16:9', quality: 'medium', steps: 20, cfg: 7, intensity: 100 },
};

export const ASPECT_RATIO_BY_NAME: Record<string, string> = {
  'cinematic-scope-239': '2.39:1',
  'standard-wide-169': '16:9',
  'academy-43': '4:3',
  'vertical-mobile-916': '9:16',
  'square-11': '1:1',
  'imax-143': '1.43:1',
  'ultra-wide-219': '21:9',
  'social-45': '4:5',
  'classic-32': '3:2',
  'portrait-23': '2:3',
  'panorama-329': '32:9',
  'ultratall-921': '9:21',
};

export function toTitleCase(value: string): string {
  return value
    .split('-')
    .map((part) => (part.length > 0 ? part[0].toUpperCase() + part.slice(1) : part))
    .join(' ');
}

export function buildPresetId(category: PresetCategory, name: string): string {
  return `builtin-${category}-${name}`;
}

export function buildPresetDescription(category: PresetCategory, name: string): string {
  return `${toTitleCase(name)} preset for ${category} control with production-ready defaults.`;
}
