// @generated by scripts/generate-preload.ts. Do not edit by hand.

import type {
  PublicWireMethodV1,
  WireFailureV1,
  WirePushV1,
  WireRequestV1,
  WireSuccessV1,
} from './wire.js';

export type DesktopCallV1<Method extends PublicWireMethodV1> = Pick<
  Extract<WireRequestV1, { readonly method: Method }>,
  'requestId' | 'input'
>;

export type DesktopResponseV1<Method extends PublicWireMethodV1> =
  | Extract<WireSuccessV1, { readonly method: Method }>
  | (Omit<WireFailureV1, 'method'> & { readonly method: Method });

export interface DesktopCanvasApiV1 {
  apply(request: DesktopCallV1<'canvas.apply'>): Promise<DesktopResponseV1<'canvas.apply'>>;
  create(request: DesktopCallV1<'canvas.create'>): Promise<DesktopResponseV1<'canvas.create'>>;
  get(request: DesktopCallV1<'canvas.get'>): Promise<DesktopResponseV1<'canvas.get'>>;
  list(request: DesktopCallV1<'canvas.list'>): Promise<DesktopResponseV1<'canvas.list'>>;
  update(request: DesktopCallV1<'canvas.update'>): Promise<DesktopResponseV1<'canvas.update'>>;
}

export interface DesktopChatApiV1 {
  archive(request: DesktopCallV1<'chat.archive'>): Promise<DesktopResponseV1<'chat.archive'>>;
  create(request: DesktopCallV1<'chat.create'>): Promise<DesktopResponseV1<'chat.create'>>;
  delete(request: DesktopCallV1<'chat.delete'>): Promise<DesktopResponseV1<'chat.delete'>>;
  list(request: DesktopCallV1<'chat.list'>): Promise<DesktopResponseV1<'chat.list'>>;
  rename(request: DesktopCallV1<'chat.rename'>): Promise<DesktopResponseV1<'chat.rename'>>;
  restore(request: DesktopCallV1<'chat.restore'>): Promise<DesktopResponseV1<'chat.restore'>>;
}

export interface DesktopConfirmationApiV1 {
  respond(
    request: DesktopCallV1<'confirmation.respond'>,
  ): Promise<DesktopResponseV1<'confirmation.respond'>>;
}

export interface DesktopDecisionApiV1 {
  protect(
    request: DesktopCallV1<'decision.protect'>,
  ): Promise<DesktopResponseV1<'decision.protect'>>;
  record(request: DesktopCallV1<'decision.record'>): Promise<DesktopResponseV1<'decision.record'>>;
}

export interface DesktopDeliveryApiV1 {
  apply(request: DesktopCallV1<'delivery.apply'>): Promise<DesktopResponseV1<'delivery.apply'>>;
  query(request: DesktopCallV1<'delivery.query'>): Promise<DesktopResponseV1<'delivery.query'>>;
}

export interface DesktopHistoryApiV1 {
  query(request: DesktopCallV1<'history.query'>): Promise<DesktopResponseV1<'history.query'>>;
}

export interface DesktopInteractionApiV1 {
  answer(
    request: DesktopCallV1<'interaction.answer'>,
  ): Promise<DesktopResponseV1<'interaction.answer'>>;
}

export interface DesktopMediaApiV1 {
  globalImport(
    request: DesktopCallV1<'media.global.import'>,
  ): Promise<DesktopResponseV1<'media.global.import'>>;
  globalList(
    request: DesktopCallV1<'media.global.list'>,
  ): Promise<DesktopResponseV1<'media.global.list'>>;
  globalRemove(
    request: DesktopCallV1<'media.global.remove'>,
  ): Promise<DesktopResponseV1<'media.global.remove'>>;
  projectAttach(
    request: DesktopCallV1<'media.project.attach'>,
  ): Promise<DesktopResponseV1<'media.project.attach'>>;
  projectDetach(
    request: DesktopCallV1<'media.project.detach'>,
  ): Promise<DesktopResponseV1<'media.project.detach'>>;
  projectLink(
    request: DesktopCallV1<'media.project.link'>,
  ): Promise<DesktopResponseV1<'media.project.link'>>;
  projectList(
    request: DesktopCallV1<'media.project.list'>,
  ): Promise<DesktopResponseV1<'media.project.list'>>;
  previewIssue(
    request: DesktopCallV1<'media.preview.issue'>,
  ): Promise<DesktopResponseV1<'media.preview.issue'>>;
}

export interface DesktopMessageApiV1 {
  list(request: DesktopCallV1<'message.list'>): Promise<DesktopResponseV1<'message.list'>>;
  send(request: DesktopCallV1<'message.send'>): Promise<DesktopResponseV1<'message.send'>>;
}

export interface DesktopOperationApiV1 {
  cancel(
    request: DesktopCallV1<'operation.cancel'>,
  ): Promise<DesktopResponseV1<'operation.cancel'>>;
  get(request: DesktopCallV1<'operation.get'>): Promise<DesktopResponseV1<'operation.get'>>;
}

export interface DesktopOsApiV1 {
  exportPick(
    request: DesktopCallV1<'os.export.pick'>,
  ): Promise<DesktopResponseV1<'os.export.pick'>>;
  mediaPick(request: DesktopCallV1<'os.media.pick'>): Promise<DesktopResponseV1<'os.media.pick'>>;
}

export interface DesktopOverviewApiV1 {
  get(request: DesktopCallV1<'overview.get'>): Promise<DesktopResponseV1<'overview.get'>>;
}

export interface DesktopPluginApiV1 {
  apply(request: DesktopCallV1<'plugin.apply'>): Promise<DesktopResponseV1<'plugin.apply'>>;
  query(request: DesktopCallV1<'plugin.query'>): Promise<DesktopResponseV1<'plugin.query'>>;
}

export interface DesktopProductionApiV1 {
  apply(request: DesktopCallV1<'production.apply'>): Promise<DesktopResponseV1<'production.apply'>>;
  query(request: DesktopCallV1<'production.query'>): Promise<DesktopResponseV1<'production.query'>>;
}

export interface DesktopProjectApiV1 {
  capabilitiesGet(
    request: DesktopCallV1<'project.capabilities.get'>,
  ): Promise<DesktopResponseV1<'project.capabilities.get'>>;
  create(request: DesktopCallV1<'project.create'>): Promise<DesktopResponseV1<'project.create'>>;
  get(request: DesktopCallV1<'project.get'>): Promise<DesktopResponseV1<'project.get'>>;
  list(request: DesktopCallV1<'project.list'>): Promise<DesktopResponseV1<'project.list'>>;
  settingsGet(
    request: DesktopCallV1<'project.settings.get'>,
  ): Promise<DesktopResponseV1<'project.settings.get'>>;
  settingsUpdate(
    request: DesktopCallV1<'project.settings.update'>,
  ): Promise<DesktopResponseV1<'project.settings.update'>>;
  update(request: DesktopCallV1<'project.update'>): Promise<DesktopResponseV1<'project.update'>>;
}

export interface DesktopResultApiV1 {
  query(request: DesktopCallV1<'result.query'>): Promise<DesktopResponseV1<'result.query'>>;
}

export interface DesktopRunApiV1 {
  control(request: DesktopCallV1<'run.control'>): Promise<DesktopResponseV1<'run.control'>>;
  eventsList(
    request: DesktopCallV1<'run.events.list'>,
  ): Promise<DesktopResponseV1<'run.events.list'>>;
  get(request: DesktopCallV1<'run.get'>): Promise<DesktopResponseV1<'run.get'>>;
  sendFollowup(
    request: DesktopCallV1<'run.sendFollowup'>,
  ): Promise<DesktopResponseV1<'run.sendFollowup'>>;
  onEventsAppended(callback: (push: WirePushV1) => void): () => void;
}

export interface DesktopSequenceApiV1 {
  apply(request: DesktopCallV1<'sequence.apply'>): Promise<DesktopResponseV1<'sequence.apply'>>;
  create(request: DesktopCallV1<'sequence.create'>): Promise<DesktopResponseV1<'sequence.create'>>;
  get(request: DesktopCallV1<'sequence.get'>): Promise<DesktopResponseV1<'sequence.get'>>;
  list(request: DesktopCallV1<'sequence.list'>): Promise<DesktopResponseV1<'sequence.list'>>;
}

export interface DesktopWindowControlsApiV1 {
  minimize(): void;
  toggleMaximize(): void;
  close(): void;
}

export interface DesktopApiV1 {
  readonly canvas: DesktopCanvasApiV1;
  readonly chat: DesktopChatApiV1;
  readonly confirmation: DesktopConfirmationApiV1;
  readonly decision: DesktopDecisionApiV1;
  readonly delivery: DesktopDeliveryApiV1;
  readonly history: DesktopHistoryApiV1;
  readonly interaction: DesktopInteractionApiV1;
  readonly media: DesktopMediaApiV1;
  readonly message: DesktopMessageApiV1;
  readonly operation: DesktopOperationApiV1;
  readonly os: DesktopOsApiV1;
  readonly overview: DesktopOverviewApiV1;
  readonly plugin: DesktopPluginApiV1;
  readonly production: DesktopProductionApiV1;
  readonly project: DesktopProjectApiV1;
  readonly result: DesktopResultApiV1;
  readonly run: DesktopRunApiV1;
  readonly sequence: DesktopSequenceApiV1;
  readonly windowControls: DesktopWindowControlsApiV1;
}
