import type { Capability } from './dto/adapter.js';
import type { OAuthProviderTarget } from './oauth-provider.js';

export type MediaProviderGroup = 'image' | 'video';
export type MediaProviderKind = 'official' | 'hub';
export type MediaProviderAccess = 'public' | 'managed' | 'excluded';

/**
 * Cross-layer source of truth for built-in media providers.
 *
 * `providerId` is the stable ID persisted by Settings and Keychain.
 * `adapterId` is the runtime transport implementation. Several model cards may
 * intentionally share one hub transport (for example Wan through Replicate).
 */
export interface BuiltinMediaProviderCatalogEntry {
  group: MediaProviderGroup;
  providerId: string;
  adapterId: string;
  credentialId: string;
  name: string;
  kind: MediaProviderKind;
  access: MediaProviderAccess;
  oauthTarget?: OAuthProviderTarget;
  baseUrl: string;
  model: string;
  modelExample?: string;
  docsUrl: string;
  keyUrl: string;
  allowedHosts: readonly string[];
  capabilities: readonly Capability[];
  supportsReferenceImage?: boolean;
  supportsAudio?: boolean;
  qualityTiers?: readonly string[];
  defaultResolution?: string;
  defaultDurationSeconds?: number;
  outputFormats: readonly string[];
  notes?: string;
  excludedReason?: string;
}

const MEDIA_PROVIDER_CATALOG = [
  // Managed and official image APIs.
  {
    group: 'image',
    providerId: 'codex-imagegen',
    adapterId: 'codex-imagegen',
    credentialId: 'codex-imagegen',
    name: 'ChatGPT Image Generation',
    kind: 'official',
    access: 'managed',
    oauthTarget: { provider: 'chatgpt', capability: 'image' },
    baseUrl: 'https://chatgpt.com',
    model: '$imagegen',
    docsUrl: 'https://learn.chatgpt.com/docs/image-generation',
    keyUrl: 'https://chatgpt.com',
    allowedHosts: ['chatgpt.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png'],
    notes: 'Uses the signed-in ChatGPT plan quota; API-key billing is not used.',
  },
  {
    group: 'image',
    providerId: 'openai-image',
    adapterId: 'openai-dalle',
    credentialId: 'openai-image',
    name: 'OpenAI GPT Image',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-image-2',
    docsUrl: 'https://developers.openai.com/api/docs/guides/image-generation',
    keyUrl: 'https://platform.openai.com/api-keys',
    allowedHosts: ['api.openai.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpeg', 'webp'],
  },
  {
    group: 'image',
    providerId: 'google-image',
    adapterId: 'google-imagen3',
    credentialId: 'google-image',
    name: 'Google Gemini Image',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    model: 'gemini-3.1-flash-image',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/image-generation',
    keyUrl: 'https://aistudio.google.com/apikey',
    allowedHosts: ['generativelanguage.googleapis.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpeg'],
    notes: 'Imagen is deprecated; Gemini 3.1 Flash Image is the supported successor.',
  },
  {
    group: 'image',
    providerId: 'recraft',
    adapterId: 'recraft-v4',
    credentialId: 'recraft',
    name: 'Recraft',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://external.api.recraft.ai/v1',
    model: 'recraftv4_1',
    docsUrl: 'https://www.recraft.ai/docs',
    keyUrl: 'https://www.recraft.ai/profile/api',
    allowedHosts: ['external.api.recraft.ai'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png'],
  },
  {
    group: 'image',
    providerId: 'ideogram',
    adapterId: 'ideogram',
    credentialId: 'ideogram',
    name: 'Ideogram',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.ideogram.ai',
    model: 'ideogram-v3',
    docsUrl: 'https://developer.ideogram.ai/',
    keyUrl: 'https://developer.ideogram.ai/',
    allowedHosts: ['api.ideogram.ai'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png'],
  },
  {
    group: 'image',
    providerId: 'zhipu-image',
    adapterId: 'zhipu-image',
    credentialId: 'zhipu-image',
    name: 'Zhipu Image',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    model: 'glm-image',
    docsUrl: 'https://docs.bigmodel.cn/cn/guide/models/image-generation/cogview-4',
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    allowedHosts: ['open.bigmodel.cn'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg'],
  },
  {
    group: 'image',
    providerId: 'leonardo',
    adapterId: 'leonardo-v2',
    credentialId: 'leonardo',
    name: 'Leonardo AI',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1',
    model: '7b592283-e8a7-4c5a-9ba6-d18c31f258b9',
    docsUrl: 'https://docs.leonardo.ai/v1.0/docs/lucid-origin',
    keyUrl: 'https://app.leonardo.ai/api-access',
    allowedHosts: ['cloud.leonardo.ai'],
    capabilities: ['text-to-image'],
    defaultResolution: '1200x1200',
    outputFormats: ['png', 'jpg'],
    notes: 'Defaults to the current Lucid Origin model ID.',
  },
  {
    group: 'image',
    providerId: 'stepfun-image',
    adapterId: 'stepfun-image',
    credentialId: 'stepfun-image',
    name: 'StepFun Image',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.stepfun.com/v1',
    model: 'step-2x-large',
    docsUrl: 'https://platform.stepfun.com/docs/zh/api-reference/images/image',
    keyUrl: 'https://platform.stepfun.com/interface-key',
    allowedHosts: ['api.stepfun.com'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg'],
  },
  {
    group: 'image',
    providerId: 'volcengine-image',
    adapterId: 'volcengine-image',
    credentialId: 'volcengine-image',
    name: 'Volcengine Seedream',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-seedream-4-0-250828',
    docsUrl:
      'https://api.volcengine.com/api-docs/view?action=ImageGenerations&serviceCode=ark&version=2024-01-01',
    keyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    allowedHosts: [
      'ark.cn-beijing.volces.com',
      'ark.ap-southeast.bytepluses.com',
      'ark.eu-west.bytepluses.com',
    ],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '2048x2048',
    outputFormats: ['jpg'],
  },
  {
    group: 'image',
    providerId: 'tongyi-wanxiang',
    adapterId: 'alibaba-wan-image',
    credentialId: 'tongyi-wanxiang',
    name: 'Alibaba Wan Image',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
    model: 'wan2.7-image-pro',
    docsUrl:
      'https://help.aliyun.com/en/model-studio/wan-image-generation-and-editing-api-reference',
    keyUrl: 'https://bailian.console.aliyun.com/',
    allowedHosts: [
      'dashscope.aliyuncs.com',
      'dashscope-intl.aliyuncs.com',
      'dashscope-us.aliyuncs.com',
      '*.cn-beijing.maas.aliyuncs.com',
      '*.ap-southeast-1.maas.aliyuncs.com',
    ],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '2048x2048',
    outputFormats: ['png'],
    notes:
      'Wan 2.7 may require a workspace-specific regional base URL; replace the base URL with the endpoint shown by Model Studio.',
  },
  {
    group: 'image',
    providerId: 'xai-imagine',
    adapterId: 'xai-imagine',
    credentialId: 'xai-imagine',
    name: 'xAI Grok Imagine',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-imagine-image-quality',
    docsUrl: 'https://docs.x.ai/developers/rest-api-reference/inference/images',
    keyUrl: 'https://console.x.ai/team/api-keys',
    allowedHosts: ['api.x.ai'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['jpeg'],
  },
  {
    group: 'image',
    providerId: 'bfl-flux',
    adapterId: 'bfl-flux',
    credentialId: 'bfl-flux',
    name: 'Black Forest Labs FLUX',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.bfl.ai/v1',
    model: 'flux-2-pro',
    docsUrl: 'https://docs.bfl.ai/quick_start/generating_images',
    keyUrl: 'https://dashboard.bfl.ai/',
    allowedHosts: ['api.bfl.ai', 'api.eu.bfl.ai', 'api.us.bfl.ai'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1440x1024',
    outputFormats: ['png', 'jpg'],
  },
  {
    group: 'image',
    providerId: 'stability-image',
    adapterId: 'stability-image',
    credentialId: 'stability-image',
    name: 'Stability AI',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.stability.ai/v2beta',
    model: 'stable-image-core',
    docsUrl: 'https://platform.stability.ai/docs/api-reference',
    keyUrl: 'https://platform.stability.ai/account/keys',
    allowedHosts: ['api.stability.ai'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpeg', 'webp'],
  },
  {
    group: 'image',
    providerId: 'bria',
    adapterId: 'bria',
    credentialId: 'bria',
    name: 'Bria AI',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://engine.prod.bria-api.com/v2',
    model: 'image/generate',
    docsUrl: 'https://docs.bria.ai/image-generation',
    keyUrl: 'https://platform.bria.ai/',
    allowedHosts: ['engine.prod.bria-api.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    qualityTiers: ['1MP', '4MP'],
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpeg'],
    notes: 'Commercially safe image generation with an official asynchronous V2 lifecycle.',
  },
  {
    group: 'image',
    providerId: 'baidu-qianfan',
    adapterId: 'baidu-qianfan',
    credentialId: 'baidu-qianfan',
    name: 'Baidu Qianfan',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://qianfan.baidubce.com',
    model: 'qwen-image',
    docsUrl: 'https://cloud.baidu.com/doc/qianfan-api/s/8m7u6un8a',
    keyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application',
    allowedHosts: ['qianfan.baidubce.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg'],
    notes: 'Uses qwen-image for generation and qwen-image-edit for one-image editing.',
  },

  // Model hubs. The configured model determines the exact model capability.
  {
    group: 'image',
    providerId: 'replicate',
    adapterId: 'replicate',
    credentialId: 'replicate',
    name: 'Replicate',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.replicate.com/v1',
    model: 'black-forest-labs/flux-2-pro',
    modelExample: 'black-forest-labs/flux-2-pro',
    docsUrl: 'https://replicate.com/docs/topics/predictions/create-a-prediction/',
    keyUrl: 'https://replicate.com/account/api-tokens',
    allowedHosts: ['api.replicate.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'image',
    providerId: 'fal',
    adapterId: 'fal-ai',
    credentialId: 'fal',
    name: 'fal',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://queue.fal.run',
    model: 'fal-ai/flux-2-pro',
    modelExample: 'fal-ai/flux-2-pro',
    docsUrl: 'https://fal.ai/docs/documentation/model-apis/inference/queue',
    keyUrl: 'https://fal.ai/dashboard/keys',
    allowedHosts: ['queue.fal.run', 'fal.run'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Capabilities and request fields depend on the selected model.',
  },
  {
    group: 'image',
    providerId: 'together',
    adapterId: 'together-ai',
    credentialId: 'together',
    name: 'Together AI',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'black-forest-labs/FLUX.1-schnell',
    modelExample: 'black-forest-labs/FLUX.1-schnell',
    docsUrl: 'https://docs.together.ai/reference/post-images-generations',
    keyUrl: 'https://api.together.ai/settings/api-keys',
    allowedHosts: ['api.together.xyz', 'api.together.ai'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'image',
    providerId: 'siliconflow-image',
    adapterId: 'siliconflow-image',
    credentialId: 'siliconflow-image',
    name: 'SiliconFlow',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.siliconflow.cn/v1',
    model: 'black-forest-labs/FLUX.1-schnell',
    modelExample: 'black-forest-labs/FLUX.1-schnell',
    docsUrl: 'https://docs.siliconflow.cn/cn/api-reference/images/images-generations',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    allowedHosts: ['api.siliconflow.cn'],
    capabilities: ['text-to-image'],
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'image',
    providerId: 'krea',
    adapterId: 'krea',
    credentialId: 'krea',
    name: 'Krea API',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.krea.ai',
    model: 'image/krea/krea-2/medium',
    modelExample: 'image/krea/krea-2/medium',
    docsUrl: 'https://www.krea.ai/docs/api-reference/krea/krea-2-medium',
    keyUrl: 'https://www.krea.ai/',
    allowedHosts: ['api.krea.ai'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Krea model paths are configurable; the adapter resolves the final job URL.',
  },
  {
    group: 'image',
    providerId: 'higgsfield',
    adapterId: 'higgsfield',
    credentialId: 'higgsfield',
    name: 'Higgsfield',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://platform.higgsfield.ai',
    model: 'bytedance/seedream/v4/text-to-image',
    modelExample: 'bytedance/seedream/v4/text-to-image',
    docsUrl: 'https://github.com/higgsfield-ai/higgsfield-js',
    keyUrl: 'https://platform.higgsfield.ai/',
    allowedHosts: ['platform.higgsfield.ai'],
    capabilities: ['text-to-image'],
    defaultResolution: '2048x2048',
    outputFormats: ['png', 'jpg', 'webp'],
    notes: 'Credentials use the official KEY_ID:KEY_SECRET format.',
  },
  {
    group: 'image',
    providerId: 'segmind',
    adapterId: 'segmind',
    credentialId: 'segmind',
    name: 'Segmind',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.segmind.com',
    model: 'seedream-5-pro',
    modelExample: 'seedream-5-pro',
    docsUrl: 'https://www.segmind.com/models/seedream-5-pro/api',
    keyUrl: 'https://www.segmind.com/',
    allowedHosts: ['api.segmind.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '2048x2048',
    outputFormats: ['jpeg', 'png'],
    notes:
      'The selected model controls request fields; completed V2 results expire after one hour.',
  },
  {
    group: 'image',
    providerId: 'freepik',
    adapterId: 'freepik',
    credentialId: 'freepik',
    name: 'Freepik API',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.freepik.com/v1/ai',
    model: 'text-to-image/flux-2-pro',
    modelExample: 'text-to-image/flux-2-pro',
    docsUrl: 'https://docs.freepik.com/api-reference/text-to-image/post-flux-2-pro',
    keyUrl: 'https://www.freepik.com/api',
    allowedHosts: ['api.freepik.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    supportsReferenceImage: true,
    defaultResolution: '1024x1024',
    outputFormats: ['png', 'jpg'],
    notes: 'Uses official Freepik task endpoints and resolves the generated asset URL.',
  },
  // Official video APIs.
  {
    group: 'video',
    providerId: 'google-video',
    adapterId: 'google-veo-2',
    credentialId: 'google-video',
    name: 'Google Gemini Video',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    model: 'gemini-omni-flash-preview',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/video',
    keyUrl: 'https://aistudio.google.com/apikey',
    allowedHosts: ['generativelanguage.googleapis.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 6,
    outputFormats: ['mp4'],
    notes:
      'Gemini Omni Flash is the current default; Veo 3.1 remains for specialized video-generation cases.',
  },
  {
    group: 'video',
    providerId: 'runway',
    adapterId: 'runway-gen4',
    credentialId: 'runway',
    name: 'Runway',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.dev.runwayml.com/v1',
    model: 'gen4.5',
    docsUrl: 'https://docs.dev.runwayml.com/guides/models/',
    keyUrl: 'https://dev.runwayml.com/',
    allowedHosts: ['api.dev.runwayml.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1920x1080',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'ltx',
    adapterId: 'ltx',
    credentialId: 'ltx',
    name: 'LTX',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.ltx.io',
    model: 'ltx-2-3-pro',
    docsUrl:
      'https://docs.ltx.io/api-documentation/api-reference/async-video-generation/submit-text-to-video',
    keyUrl: 'https://console.ltx.video/',
    allowedHosts: ['api.ltx.io'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1920x1080',
    defaultDurationSeconds: 8,
    outputFormats: ['mp4'],
    notes:
      'LTX 2.3 supports text, first/last frames, and generated audio. Audio-to-video input requires a future typed audio-source contract.',
  },
  {
    group: 'video',
    providerId: 'luma',
    adapterId: 'luma-ray2',
    credentialId: 'luma',
    name: 'Luma Dream Machine',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.lumalabs.ai/dream-machine/v1',
    model: 'ray-2',
    docsUrl: 'https://docs.lumalabs.ai/docs/video-generation',
    keyUrl: 'https://lumalabs.ai/dream-machine/api',
    allowedHosts: ['api.lumalabs.ai'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1920x1080',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'minimax',
    adapterId: 'minimax-video01',
    credentialId: 'minimax',
    name: 'MiniMax H3',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.minimax.io',
    model: 'MiniMax-H3',
    docsUrl: 'https://platform.minimax.io/docs/guides/video-generation',
    keyUrl: 'https://platform.minimax.io/user-center/basic-information/interface-key',
    allowedHosts: ['api.minimax.io'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '2048x1152',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'H3 supports 4–15 second 768P/2K generation, native stereo audio, first/last frames, and multimodal references. Legacy Hailuo 2.3 models remain accepted by the adapter.',
  },
  {
    group: 'video',
    providerId: 'kling',
    adapterId: 'kling-v1',
    credentialId: 'kling',
    name: 'Kling AI',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api-beijing.klingai.com/v1',
    model: 'kling-v3',
    docsUrl: 'https://app.klingai.com/cn/quickstart/klingai-video-3-model-user-guide',
    keyUrl: 'https://platform.klingai.com',
    allowedHosts: ['api.klingai.com', 'api-beijing.klingai.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    qualityTiers: ['std', 'pro'],
    defaultResolution: '1920x1080',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'zhipu-video',
    adapterId: 'zhipu-video',
    credentialId: 'zhipu-video',
    name: 'Zhipu CogVideoX',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    model: 'cogvideox-3',
    docsUrl: 'https://docs.bigmodel.cn/cn/guide/models/video-generation/cogvideox-3',
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    allowedHosts: ['open.bigmodel.cn'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1920x1080',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'vidu',
    adapterId: 'vidu',
    credentialId: 'vidu',
    name: 'Vidu',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.vidu.com',
    model: 'viduq3-pro',
    docsUrl: 'https://platform.vidu.com/docs/text-to-video',
    keyUrl: 'https://platform.vidu.com/',
    allowedHosts: ['api.vidu.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'volcengine-video',
    adapterId: 'volcengine-video',
    credentialId: 'volcengine-video',
    name: 'Volcengine Seedance',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'seedance-2.0',
    docsUrl:
      'https://api.volcengine.com/api-docs/view?action=CreateContentsGenerationsTasks&serviceCode=ark&version=2024-01-01',
    keyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    allowedHosts: [
      'ark.cn-beijing.volces.com',
      'ark.ap-southeast.bytepluses.com',
      'ark.eu-west.bytepluses.com',
    ],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'The model field may need a region-specific model or endpoint ID. BytePlus ModelArk Asia-Pacific and Europe data-plane hosts are supported.',
  },
  {
    group: 'video',
    providerId: 'alibaba-wan-video',
    adapterId: 'alibaba-wan-video',
    credentialId: 'tongyi-wanxiang',
    name: 'Alibaba Wan Video',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
    model: 'wan2.7-t2v',
    docsUrl: 'https://help.aliyun.com/en/model-studio/text-to-video-api-reference',
    keyUrl: 'https://bailian.console.aliyun.com/',
    allowedHosts: [
      'dashscope.aliyuncs.com',
      'dashscope-intl.aliyuncs.com',
      'dashscope-us.aliyuncs.com',
      '*.cn-beijing.maas.aliyuncs.com',
      '*.ap-southeast-1.maas.aliyuncs.com',
    ],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    qualityTiers: ['720P', '1080P'],
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'Uses Wan 2.7 text, first/last-frame, and ordered reference-to-video routes. Workspace-specific Model Studio base URLs can be configured for the selected region.',
  },
  {
    group: 'video',
    providerId: 'baidu-qianfan',
    adapterId: 'baidu-qianfan',
    credentialId: 'baidu-qianfan',
    name: 'Baidu Qianfan Video',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://qianfan.baidubce.com',
    model: 'K3.0',
    docsUrl: 'https://cloud.baidu.com/doc/qianfan-api/s/Eml7rnswy',
    keyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application',
    allowedHosts: ['qianfan.baidubce.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    qualityTiers: ['std', 'pro'],
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Uses K3.0 for text-to-video and VQ3-Turbo for one-image video generation.',
  },
  {
    group: 'video',
    providerId: 'xai-imagine',
    adapterId: 'xai-imagine',
    credentialId: 'xai-imagine',
    name: 'xAI Grok Imagine',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-imagine-video',
    docsUrl: 'https://docs.x.ai/developers/rest-api-reference/inference/videos',
    keyUrl: 'https://console.x.ai/team/api-keys',
    allowedHosts: ['api.x.ai'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 6,
    outputFormats: ['mp4'],
  },
  {
    group: 'video',
    providerId: 'pixverse',
    adapterId: 'pixverse',
    credentialId: 'pixverse',
    name: 'PixVerse',
    kind: 'official',
    access: 'public',
    baseUrl: 'https://app-api.pixverse.ai',
    model: 'v6',
    docsUrl: 'https://docs.platform.pixverse.ai/v6-2056814m0',
    keyUrl: 'https://platform.pixverse.ai/',
    allowedHosts: ['app-api.pixverse.ai'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    qualityTiers: ['360p', '540p', '720p', '1080p'],
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'V6 supports 1–15 second generation. The current adapter rejects unverified last-frame transition payloads explicitly.',
  },

  // Hub-backed video model cards.
  {
    group: 'video',
    providerId: 'replicate',
    adapterId: 'replicate',
    credentialId: 'replicate',
    name: 'Replicate',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.replicate.com/v1',
    model: 'minimax/hailuo-2.3',
    modelExample: 'minimax/hailuo-2.3',
    docsUrl: 'https://replicate.com/docs/topics/predictions/create-a-prediction/',
    keyUrl: 'https://replicate.com/account/api-tokens',
    allowedHosts: ['api.replicate.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'video',
    providerId: 'fal',
    adapterId: 'fal-ai',
    credentialId: 'fal',
    name: 'fal',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://queue.fal.run',
    model: 'minimax/h3/text-to-video',
    modelExample: 'minimax/h3/text-to-video',
    docsUrl: 'https://fal.ai/docs/documentation/model-apis/inference/queue',
    keyUrl: 'https://fal.ai/dashboard/keys',
    allowedHosts: ['queue.fal.run', 'fal.run'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'Defaults to MiniMax H3 and automatically selects its text, first/last-frame, or reference endpoint from the request. Other fal models remain configurable.',
  },
  {
    group: 'video',
    providerId: 'together',
    adapterId: 'together-ai',
    credentialId: 'together',
    name: 'Together AI',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'Wan-AI/wan2.7-t2v',
    modelExample: 'Wan-AI/wan2.7-t2v',
    docsUrl: 'https://docs.together.ai/docs/inference/videos/overview',
    keyUrl: 'https://api.together.ai/settings/api-keys',
    allowedHosts: ['api.together.xyz', 'api.together.ai'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 6,
    outputFormats: ['mp4', 'webm'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'video',
    providerId: 'siliconflow-video',
    adapterId: 'siliconflow-video',
    credentialId: 'siliconflow-video',
    name: 'SiliconFlow',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.siliconflow.cn/v1',
    model: 'Wan-AI/Wan2.2-T2V-A14B',
    modelExample: 'Wan-AI/Wan2.2-T2V-A14B',
    docsUrl: 'https://docs.siliconflow.cn/cn/api-reference/videos/videos_submit',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    allowedHosts: ['api.siliconflow.cn'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Capabilities depend on the selected model.',
  },
  {
    group: 'video',
    providerId: 'krea',
    adapterId: 'krea',
    credentialId: 'krea',
    name: 'Krea API',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.krea.ai',
    model: 'video/minimax/hailuo-2.3',
    modelExample: 'video/minimax/hailuo-2.3',
    docsUrl: 'https://www.krea.ai/docs/api-reference/video/hailuo-23',
    keyUrl: 'https://www.krea.ai/',
    allowedHosts: ['api.krea.ai'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 6,
    outputFormats: ['mp4'],
    notes: 'Krea model paths are configurable; the adapter resolves and can cancel the async job.',
  },
  {
    group: 'video',
    providerId: 'higgsfield',
    adapterId: 'higgsfield',
    credentialId: 'higgsfield',
    name: 'Higgsfield',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://platform.higgsfield.ai',
    model: '/v1/image2video/dop',
    modelExample: '/v1/image2video/dop',
    docsUrl: 'https://github.com/higgsfield-ai/higgsfield-js',
    keyUrl: 'https://platform.higgsfield.ai/',
    allowedHosts: ['platform.higgsfield.ai'],
    capabilities: ['image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'DoP is image-conditioned; credentials use the official KEY_ID:KEY_SECRET format.',
  },
  {
    group: 'video',
    providerId: 'segmind',
    adapterId: 'segmind',
    credentialId: 'segmind',
    name: 'Segmind',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.segmind.com',
    model: 'seedance-2.0',
    modelExample: 'seedance-2.0',
    docsUrl: 'https://www.segmind.com/models/seedance-2.0/api',
    keyUrl: 'https://www.segmind.com/',
    allowedHosts: ['api.segmind.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    qualityTiers: ['480p', '720p', '1080p', '4k'],
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Seedance 2.0 supports 4–15 seconds, ordered references, first/last frames, and audio.',
  },
  {
    group: 'video',
    providerId: 'freepik',
    adapterId: 'freepik',
    credentialId: 'freepik',
    name: 'Freepik API',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.freepik.com/v1/ai',
    model: 'text-to-video/runway-4-5',
    modelExample: 'text-to-video/runway-4-5',
    docsUrl: 'https://docs.freepik.com/api-reference/video/runway-gen-4-5/generate-t2v',
    keyUrl: 'https://www.freepik.com/api',
    allowedHosts: ['api.freepik.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes:
      'Uses Runway 4.5 for text-to-video and the official Veo 3.1 Fast route for image-conditioned requests.',
  },
  {
    group: 'video',
    providerId: 'seedance',
    adapterId: 'seedance-2',
    credentialId: 'seedance',
    name: 'Seedance (via Replicate)',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.replicate.com/v1',
    model: 'bytedance/seedance-2.0',
    docsUrl: 'https://replicate.com/bytedance',
    keyUrl: 'https://replicate.com/account/api-tokens',
    allowedHosts: ['api.replicate.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    supportsAudio: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Uses Replicate transport; enter a Replicate API token.',
  },
  {
    group: 'video',
    providerId: 'hunyuan',
    adapterId: 'replicate',
    credentialId: 'hunyuan',
    name: 'HunyuanVideo (via Replicate)',
    kind: 'hub',
    access: 'public',
    baseUrl: 'https://api.replicate.com/v1',
    model: 'tencent/hunyuan-video',
    docsUrl: 'https://replicate.com/tencent',
    keyUrl: 'https://replicate.com/account/api-tokens',
    allowedHosts: ['api.replicate.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    supportsReferenceImage: true,
    defaultResolution: '1280x720',
    defaultDurationSeconds: 5,
    outputFormats: ['mp4'],
    notes: 'Uses Replicate transport; enter a Replicate API token.',
  },

  // Explicitly researched exclusions: never render these as working built-ins.
  {
    group: 'image',
    providerId: 'adobe-firefly',
    adapterId: 'adobe-firefly',
    credentialId: 'adobe-firefly',
    name: 'Adobe Firefly',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://firefly-api.adobe.io',
    model: 'firefly-image-5',
    docsUrl: 'https://developer.adobe.com/firefly-services/docs/firefly-api/',
    keyUrl: 'https://developer.adobe.com/console',
    allowedHosts: ['firefly-api.adobe.io'],
    capabilities: ['text-to-image', 'image-to-image'],
    outputFormats: ['png', 'jpg'],
    excludedReason:
      'Requires both an Adobe client ID and OAuth access token; the current single-secret credential contract cannot represent it safely.',
  },
  {
    group: 'video',
    providerId: 'adobe-firefly',
    adapterId: 'adobe-firefly-video',
    credentialId: 'adobe-firefly',
    name: 'Adobe Firefly Video',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://firefly-api.adobe.io',
    model: 'firefly-video',
    docsUrl: 'https://developer.adobe.com/firefly-services/docs/firefly-api/',
    keyUrl: 'https://developer.adobe.com/console',
    allowedHosts: ['firefly-api.adobe.io'],
    capabilities: ['text-to-video', 'image-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'Requires both an Adobe client ID and OAuth access token; the current single-secret credential contract cannot represent and refresh them safely.',
  },
  {
    group: 'image',
    providerId: 'midjourney',
    adapterId: 'midjourney',
    credentialId: 'midjourney',
    name: 'Midjourney',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://www.midjourney.com',
    model: '',
    docsUrl: 'https://docs.midjourney.com/',
    keyUrl: 'https://www.midjourney.com/',
    allowedHosts: ['www.midjourney.com'],
    capabilities: ['text-to-image'],
    outputFormats: ['png'],
    excludedReason: 'No generally available, officially documented public generation API.',
  },
  {
    group: 'video',
    providerId: 'openai-sora',
    adapterId: 'openai-sora',
    credentialId: 'openai-sora',
    name: 'OpenAI Sora API',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://api.openai.com/v1',
    model: 'sora-2',
    docsUrl: 'https://developers.openai.com/api/docs/guides/video-generation',
    keyUrl: 'https://platform.openai.com/api-keys',
    allowedHosts: ['api.openai.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'The current OpenAI Sora API documentation is marked legacy/deprecated; it is not advertised as a current built-in.',
  },
  {
    group: 'video',
    providerId: 'pika',
    adapterId: 'pika-v2',
    credentialId: 'pika',
    name: 'Pika',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://devapi.pika.art',
    model: 'pika-2.5',
    docsUrl: 'https://pika.art/api',
    keyUrl: 'https://fal.ai/dashboard/keys',
    allowedHosts: ['devapi.pika.art'],
    capabilities: ['text-to-video', 'image-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'Pika directs general API users to fal; use a fal Pika model instead of an unverified direct lifecycle.',
  },
  {
    group: 'video',
    providerId: 'stepfun-video',
    adapterId: 'stepfun-video',
    credentialId: 'stepfun-video',
    name: 'StepFun Video',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://api.stepfun.com/v1',
    model: '',
    docsUrl: 'https://platform.stepfun.com/docs/',
    keyUrl: 'https://platform.stepfun.com/interface-key',
    allowedHosts: ['api.stepfun.com'],
    capabilities: ['text-to-video'],
    outputFormats: ['mp4'],
    excludedReason: 'No public production video-generation API could be verified in official docs.',
  },
  {
    group: 'video',
    providerId: 'amazon-nova-reel',
    adapterId: 'amazon-nova-reel',
    credentialId: 'amazon-bedrock',
    name: 'Amazon Nova Reel',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    model: 'amazon.nova-reel-v1:1',
    docsUrl: 'https://docs.aws.amazon.com/nova/latest/userguide/video-generation.html',
    keyUrl: 'https://console.aws.amazon.com/iam/',
    allowedHosts: ['bedrock-runtime.us-east-1.amazonaws.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'Requires structured AWS credentials, SigV4, a region, and a customer-owned S3 output destination; the current credential and artifact contracts cannot represent that lifecycle safely.',
  },
  {
    group: 'image',
    providerId: 'amazon-nova-canvas',
    adapterId: 'amazon-nova-canvas',
    credentialId: 'amazon-bedrock',
    name: 'Amazon Nova Canvas',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    model: 'amazon.nova-canvas-v1:0',
    docsUrl: 'https://docs.aws.amazon.com/nova/latest/userguide/image-generation.html',
    keyUrl: 'https://console.aws.amazon.com/iam/',
    allowedHosts: ['bedrock-runtime.us-east-1.amazonaws.com'],
    capabilities: ['text-to-image', 'image-to-image'],
    outputFormats: ['png', 'jpeg'],
    excludedReason:
      'Requires structured AWS credentials, SigV4, and a region, and AWS has announced model end-of-support for 2026-09-30; it is not suitable as a new built-in default.',
  },
  {
    group: 'video',
    providerId: 'tencent-hunyuan-video',
    adapterId: 'tencent-hunyuan-video',
    credentialId: 'tencent-cloud',
    name: 'Tencent Hunyuan Video',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    model: 'hunyuan-video',
    docsUrl: 'https://cloud.tencent.com/document/product/1616/126160',
    keyUrl: 'https://console.cloud.tencent.com/cam/capi',
    allowedHosts: ['hunyuan.tencentcloudapi.com'],
    capabilities: ['text-to-video', 'image-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'Requires SecretId, SecretKey, region, and TC3-HMAC request signing; the current single-secret credential contract cannot represent it safely. Hunyuan remains available through Replicate.',
  },
  {
    group: 'video',
    providerId: 'heygen-avatar-video',
    adapterId: 'heygen-avatar-video',
    credentialId: 'heygen',
    name: 'HeyGen Avatar Video',
    kind: 'official',
    access: 'excluded',
    baseUrl: 'https://api.heygen.com',
    model: 'avatar-video',
    docsUrl: 'https://docs.heygen.com/',
    keyUrl: 'https://app.heygen.com/settings?nav=API',
    allowedHosts: ['api.heygen.com'],
    capabilities: ['text-to-video'],
    outputFormats: ['mp4'],
    excludedReason:
      'Avatar generation requires typed avatar, voice, script, template, and consent fields. It needs a dedicated avatar-video contract instead of the generic shot-generation adapter.',
  },
] as const satisfies readonly BuiltinMediaProviderCatalogEntry[];

function cloneEntry(entry: BuiltinMediaProviderCatalogEntry): BuiltinMediaProviderCatalogEntry {
  return {
    ...entry,
    allowedHosts: [...entry.allowedHosts],
    oauthTarget: entry.oauthTarget ? { ...entry.oauthTarget } : undefined,
    capabilities: [...entry.capabilities],
    qualityTiers: entry.qualityTiers ? [...entry.qualityTiers] : undefined,
    outputFormats: [...entry.outputFormats],
  };
}

export function listBuiltinMediaProviders(
  group?: MediaProviderGroup,
  options: { includeExcluded?: boolean } = {},
): BuiltinMediaProviderCatalogEntry[] {
  return MEDIA_PROVIDER_CATALOG.filter((entry) => (group ? entry.group === group : true))
    .filter((entry) => options.includeExcluded || entry.access !== 'excluded')
    .map(cloneEntry);
}

export function getBuiltinMediaProvider(
  group: MediaProviderGroup,
  providerId: string,
  options: { includeExcluded?: boolean } = {},
): BuiltinMediaProviderCatalogEntry | undefined {
  const normalizedId = providerId.trim().toLowerCase();
  const entry = MEDIA_PROVIDER_CATALOG.find(
    (candidate) => candidate.group === group && candidate.providerId === normalizedId,
  );
  if (!entry || (!options.includeExcluded && entry.access === 'excluded')) return undefined;
  return cloneEntry(entry);
}

export function resolveBuiltinMediaAdapterId(
  providerId: string,
  group: MediaProviderGroup,
): string | undefined {
  return getBuiltinMediaProvider(group, providerId)?.adapterId;
}

export function resolveBuiltinMediaCredentialId(
  providerId: string,
  group: MediaProviderGroup,
): string | undefined {
  return getBuiltinMediaProvider(group, providerId)?.credentialId;
}

/** Resolve a provider ID when every media group maps it to the same transport. */
export function resolveUnambiguousBuiltinMediaAdapterId(providerId: string): string | undefined {
  const normalizedId = providerId.trim().toLowerCase();
  const adapterIds = new Set(
    MEDIA_PROVIDER_CATALOG.filter(
      (entry) => entry.access !== 'excluded' && entry.providerId === normalizedId,
    ).map((entry) => entry.adapterId),
  );
  return adapterIds.size === 1 ? [...adapterIds][0] : undefined;
}
