// @generated by scripts/gen-preload.ts. Do not edit by hand.
import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('lucidAPI', {
  health: {
    ping: async (req: unknown) => ipcRenderer.invoke('health:ping', req),
  },
});
