// @generated by scripts/generate-preload.ts. Do not edit by hand.
import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron';

const INVOKE_CHANNEL = 'lucid-fin:wire:v1';
const PUSH_CHANNEL = 'lucid-fin:push:v1';

interface DesktopCall {
  readonly requestId: string;
  readonly input: unknown;
}

function invoke(method: string, request: DesktopCall): Promise<unknown> {
  return ipcRenderer.invoke(INVOKE_CHANNEL, {
    wireVersion: 1,
    kind: 'request',
    requestId: request.requestId,
    method,
    input: request.input,
  });
}

function onRunEventsAppended(callback: (push: unknown) => void): () => void {
  const listener = (_event: IpcRendererEvent, push: unknown) => callback(push);
  ipcRenderer.on(PUSH_CHANNEL, listener);
  return () => ipcRenderer.removeListener(PUSH_CHANNEL, listener);
}

contextBridge.exposeInMainWorld('lucidFin', {
  canvas: {
    apply: (request: DesktopCall) => invoke('canvas.apply', request),
    get: (request: DesktopCall) => invoke('canvas.get', request),
  },
  chat: {
    archive: (request: DesktopCall) => invoke('chat.archive', request),
    create: (request: DesktopCall) => invoke('chat.create', request),
    delete: (request: DesktopCall) => invoke('chat.delete', request),
    list: (request: DesktopCall) => invoke('chat.list', request),
    rename: (request: DesktopCall) => invoke('chat.rename', request),
  },
  confirmation: {
    respond: (request: DesktopCall) => invoke('confirmation.respond', request),
  },
  decision: {
    protect: (request: DesktopCall) => invoke('decision.protect', request),
    record: (request: DesktopCall) => invoke('decision.record', request),
  },
  delivery: {
    apply: (request: DesktopCall) => invoke('delivery.apply', request),
    query: (request: DesktopCall) => invoke('delivery.query', request),
  },
  history: {
    query: (request: DesktopCall) => invoke('history.query', request),
  },
  interaction: {
    answer: (request: DesktopCall) => invoke('interaction.answer', request),
  },
  media: {
    globalImport: (request: DesktopCall) => invoke('media.global.import', request),
    globalList: (request: DesktopCall) => invoke('media.global.list', request),
    globalRemove: (request: DesktopCall) => invoke('media.global.remove', request),
    projectAttach: (request: DesktopCall) => invoke('media.project.attach', request),
    projectDetach: (request: DesktopCall) => invoke('media.project.detach', request),
    projectLink: (request: DesktopCall) => invoke('media.project.link', request),
    projectList: (request: DesktopCall) => invoke('media.project.list', request),
    previewIssue: (request: DesktopCall) => invoke('media.preview.issue', request),
  },
  message: {
    list: (request: DesktopCall) => invoke('message.list', request),
    send: (request: DesktopCall) => invoke('message.send', request),
  },
  operation: {
    cancel: (request: DesktopCall) => invoke('operation.cancel', request),
    get: (request: DesktopCall) => invoke('operation.get', request),
  },
  os: {
    exportPick: (request: DesktopCall) => invoke('os.export.pick', request),
    mediaPick: (request: DesktopCall) => invoke('os.media.pick', request),
  },
  overview: {
    get: (request: DesktopCall) => invoke('overview.get', request),
  },
  plugin: {
    apply: (request: DesktopCall) => invoke('plugin.apply', request),
    query: (request: DesktopCall) => invoke('plugin.query', request),
  },
  production: {
    apply: (request: DesktopCall) => invoke('production.apply', request),
    query: (request: DesktopCall) => invoke('production.query', request),
  },
  project: {
    capabilitiesGet: (request: DesktopCall) => invoke('project.capabilities.get', request),
    create: (request: DesktopCall) => invoke('project.create', request),
    get: (request: DesktopCall) => invoke('project.get', request),
    list: (request: DesktopCall) => invoke('project.list', request),
    settingsGet: (request: DesktopCall) => invoke('project.settings.get', request),
    settingsUpdate: (request: DesktopCall) => invoke('project.settings.update', request),
    update: (request: DesktopCall) => invoke('project.update', request),
  },
  result: {
    query: (request: DesktopCall) => invoke('result.query', request),
  },
  run: {
    control: (request: DesktopCall) => invoke('run.control', request),
    eventsList: (request: DesktopCall) => invoke('run.events.list', request),
    get: (request: DesktopCall) => invoke('run.get', request),
    sendFollowup: (request: DesktopCall) => invoke('run.sendFollowup', request),
    onEventsAppended: onRunEventsAppended,
  },
});
