import { TaskKind } from '@lucid-fin/contracts';
import type { RegisteredTaskListBlueprint } from '../task-list-registry.js';

export const styleExtractTaskList: RegisteredTaskListBlueprint = {
  id: 'style.extract',
  name: 'Extract style',
  version: 1,
  kind: 'style.extract',
  description:
    'Extract a reusable color and lighting profile from an imported image or video asset.',
  displayCategory: 'Style',
  displayLabel: 'Extract style',
  displayLabelKey: 'taskListLabels.extractStyle',
  summary: 'Extract a reusable style profile from a reference asset.',
  tasks: [
    {
      id: 'resolve-style-asset',
      name: 'Resolve style asset',
      phaseKey: 'resolve',
      phaseName: 'Resolve source asset',
      phaseOrder: 0,
      kind: TaskKind.AssetResolve,
      handlerId: 'style.resolve-asset',
      maxRetries: 1,
      displayCategory: 'Style',
      displayLabel: 'Resolve source asset',
      displayLabelKey: 'taskLabels.resolveStyleAsset',
      summary: 'Resolve the source image or video and prepare provider-ready input data.',
    },
    {
      id: 'extract-style-profile',
      name: 'Extract style profile',
      phaseKey: 'extract',
      phaseName: 'Extract style profile',
      phaseOrder: 1,
      kind: TaskKind.MetadataExtract,
      handlerId: 'style.extract.profile',
      maxRetries: 2,
      dependsOnTaskIds: ['resolve-style-asset'],
      displayCategory: 'Style',
      displayLabel: 'Extract style profile',
      displayLabelKey: 'taskLabels.extractStyleProfile',
      promptTemplateId: 'style.extract.profile',
      promptTemplateVersion: '1.0.0',
      summary: 'Extract palette, gradients, and exposure data from the source asset.',
    },
    {
      id: 'persist-style-profile',
      name: 'Persist style profile',
      phaseKey: 'persist',
      phaseName: 'Persist extracted style',
      phaseOrder: 2,
      kind: TaskKind.Transform,
      handlerId: 'style.persist',
      maxRetries: 1,
      dependsOnTaskIds: ['extract-style-profile'],
      displayCategory: 'Style',
      displayLabel: 'Persist extracted style',
      displayLabelKey: 'taskLabels.persistStyleProfile',
      summary: 'Save the extracted style profile as a reusable color style entry.',
    },
  ],
};
