import { z } from 'zod';

export const EXACT_TOOL_IDS = Object.freeze([
  'agent.cancel',
  'agent.result',
  'agent.send',
  'agent.spawn',
  'agent.wait',
  'canvas.mutate',
  'canvas.query',
  'chat.query',
  'decision.protect',
  'decision.record',
  'delivery.export',
  'delivery.freeze',
  'delivery.mutate',
  'delivery.preview',
  'delivery.query',
  'evaluation.run',
  'generation.quote',
  'generation.submit',
  'history.query',
  'interaction.ask',
  'media.attach',
  'media.derive',
  'media.inspect',
  'media.link',
  'media.query',
  'memory.query',
  'operation.cancel',
  'operation.get',
  'production.mutate',
  'production.query',
  'project.get',
  'project.search',
  'provider.capabilities',
  'result.query',
  'run.inspect',
  'skill.load',
  'skill.propose',
  'task.manage',
  'tool.get',
  'tool.program',
] as const);

export const ToolIdSchema = z.enum(EXACT_TOOL_IDS);
export type ToolId = z.infer<typeof ToolIdSchema>;
