export type Locale = 'en-US' | 'zh-CN';

const COPY = {
  'en-US': {
    projects: 'Projects',
    globalMedia: 'Global Media',
    settings: 'Settings',
    newProject: 'New Project',
    describeFilm: 'Describe the film you want to make…',
    attachReference: 'Attach reference',
    createAndStart: 'Create project & start',
    overview: 'Overview',
    canvas: 'Canvas',
    media: 'Media',
    production: 'Production',
    delivery: 'Delivery',
    commander: 'Commander',
    newChat: 'New Chat',
    search: 'Search',
    focus: 'Focus',
    exitFocus: 'Exit Focus',
    send: 'Send',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    retry: 'Retry',
    loading: 'Loading project…',
    noProjects: 'Start with a sentence or a reference.',
    noConversation: 'Tell Commander what you want to make or change.',
    noWorkspaceData: 'No project material here yet.',
    context: 'Context',
    activeWork: 'Active work',
    decisions: 'Needs your decision',
    recentChanges: 'Recent project changes',
    permission: 'Permission',
    budget: 'Budget',
    model: 'Model',
    projectMenu: 'Project menu',
    openCommander: 'Open Commander',
    backToProjects: 'Back to Projects',
    unsupported: 'Unavailable until the owning owning command is implemented.',
    skillHint: 'Ask Commander to add a Skill. Activation always waits for your confirmation.',
  },
  'zh-CN': {
    projects: '项目',
    globalMedia: '全局媒体',
    settings: '设置',
    newProject: '新建项目',
    describeFilm: '描述你想制作的影片…',
    attachReference: '添加参考',
    createAndStart: '创建项目并开始',
    overview: '概览',
    canvas: '画布',
    media: '媒体',
    production: '制作',
    delivery: '交付',
    commander: 'Commander',
    newChat: '新建对话',
    search: '搜索',
    focus: '专注',
    exitFocus: '退出专注',
    send: '发送',
    stop: '停止',
    pause: '暂停',
    resume: '继续',
    retry: '重试',
    loading: '正在载入项目…',
    noProjects: '从一句描述或一份参考开始。',
    noConversation: '告诉 Commander 你想制作或修改什么。',
    noWorkspaceData: '这里还没有项目素材。',
    context: '上下文',
    activeWork: '进行中的工作',
    decisions: '需要你的决定',
    recentChanges: '最近项目变更',
    permission: '权限',
    budget: '预算',
    model: '模型',
    projectMenu: '项目菜单',
    openCommander: '打开 Commander',
    backToProjects: '返回项目',
    unsupported: '拥有该能力的对应命令尚未实现，因此暂不可用。',
    skillHint: '请直接让 Commander 添加 Skill；激活前始终需要你的确认。',
  },
} as const;

export type CopyKey = keyof (typeof COPY)['en-US'];

export function appCopy(locale: Locale, key: CopyKey): string {
  return COPY[locale][key];
}
