/**
 * Task-execution table constants.
 *
 * Covers the durable task-list graph without a separate phase entity.
 */
import type { TaskListId, TaskId, AssetHash } from '@lucid-fin/contracts';
import { defineTable, col } from '../../tables.js';

export const TaskListsTable = defineTable('task_lists', {
  id: col<TaskListId>('id'),
  taskListType: col<string>('task_list_type'),
  entityType: col<string>('entity_type'),
  entityId: col<string | null>('entity_id'),
  triggerSource: col<string>('trigger_source'),
  status: col<string>('status'),
  summary: col<string>('summary'),
  progress: col<number>('progress'),
  completedPhases: col<number>('completed_phases'),
  totalPhases: col<number>('total_phases'),
  completedTasks: col<number>('completed_tasks'),
  totalTasks: col<number>('total_tasks'),
  currentPhaseKey: col<string | null>('current_phase_key'),
  currentTaskId: col<TaskId | null>('current_task_id'),
  inputJson: col<string>('input_json'),
  outputJson: col<string>('output_json'),
  errorText: col<string | null>('error_text'),
  metadataJson: col<string>('metadata_json'),
  createdAt: col<number>('created_at'),
  startedAt: col<number | null>('started_at'),
  completedAt: col<number | null>('completed_at'),
  updatedAt: col<number>('updated_at'),
  rowVersion: col<number>('row_version'),
  currentGate: col<string | null>('current_gate'),
  engineVersion: col<string>('engine_version'),
  definitionVersion: col<number>('definition_version'),
  leaseOwner: col<string | null>('lease_owner'),
  leaseToken: col<number>('lease_token'),
  leaseExpiresAt: col<number | null>('lease_expires_at'),
  heartbeatAt: col<number | null>('heartbeat_at'),
});

export const PlanDocumentsTable = defineTable('plan_documents', {
  id: col<string>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  logicalKey: col<string>('logical_key'),
  documentType: col<string>('document_type'),
  revision: col<number>('revision'),
  schemaVersion: col<number>('schema_version'),
  contentJson: col<string>('content_json'),
  contentHash: col<string>('content_hash'),
  status: col<string>('status'),
  createdAt: col<number>('created_at'),
  updatedAt: col<number>('updated_at'),
});

export const PlanApprovalsTable = defineTable('plan_approvals', {
  id: col<string>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  gateKey: col<string>('gate_key'),
  subjectLogicalKey: col<string>('subject_logical_key'),
  subjectRevision: col<number>('subject_revision'),
  subjectHash: col<string>('subject_hash'),
  manifestHash: col<string>('manifest_hash'),
  resumeTokenHash: col<string>('resume_token_hash'),
  status: col<string>('status'),
  createdAt: col<number>('created_at'),
  updatedAt: col<number>('updated_at'),
  decidedAt: col<number | null>('decided_at'),
});

export const TaskEventsTable = defineTable('task_events', {
  taskListId: col<TaskListId>('task_list_id'),
  seq: col<number>('seq'),
  eventId: col<string>('event_id'),
  actor: col<string>('actor'),
  correlationId: col<string | null>('correlation_id'),
  causationId: col<string | null>('causation_id'),
  payloadJson: col<string>('payload_json'),
  eventTimestamp: col<number>('event_timestamp'),
});

export const TaskDecisionsTable = defineTable('task_decisions', {
  id: col<string>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  taskId: col<TaskId>('task_id'),
  canvasId: col<string>('canvas_id'),
  questionId: col<string>('question_id'),
  decisionKey: col<string>('decision_key'),
  subjectRevision: col<number>('subject_revision'),
  question: col<string>('question'),
  optionsJson: col<string>('options_json'),
  allowFreeText: col<number>('allow_free_text'),
  status: col<string>('status'),
  answer: col<string | null>('answer'),
  selectedOptionId: col<string | null>('selected_option_id'),
  rowVersion: col<number>('row_version'),
  createdAt: col<number>('created_at'),
  updatedAt: col<number>('updated_at'),
  answeredAt: col<number | null>('answered_at'),
});

export const TaskAttemptsTable = defineTable('task_attempts', {
  id: col<string>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  taskId: col<TaskId | null>('task_id'),
  kind: col<string>('kind'),
  manifestRevision: col<number | null>('manifest_revision'),
  manifestHash: col<string | null>('manifest_hash'),
  idempotencyKey: col<string>('idempotency_key'),
  status: col<string>('status'),
  rowVersion: col<number>('row_version'),
  stagingPath: col<string | null>('staging_path'),
  destinationPath: col<string | null>('destination_path'),
  packageHash: col<string | null>('package_hash'),
  packageBytes: col<number | null>('package_bytes'),
  fileCount: col<number | null>('file_count'),
  attempt: col<number>('attempt'),
  canvasId: col<string | null>('canvas_id'),
  nodeId: col<string | null>('node_id'),
  scope: col<string | null>('scope'),
  parentAttemptId: col<string | null>('parent_attempt_id'),
  submissionPurpose: col<string | null>('submission_purpose'),
  specHash: col<string | null>('spec_hash'),
  generationSpecJson: col<string | null>('generation_spec_json'),
  repairDeltaJson: col<string | null>('repair_delta_json'),
  mediaType: col<string | null>('media_type'),
  providerId: col<string | null>('provider_id'),
  model: col<string | null>('model'),
  prompt: col<string | null>('prompt'),
  promptHash: col<string | null>('prompt_hash'),
  negativePrompt: col<string | null>('negative_prompt'),
  seed: col<number | null>('seed'),
  estimatedCostUsd: col<number | null>('estimated_cost_usd'),
  reportedActualCostUsd: col<number | null>('reported_actual_cost_usd'),
  providerJobId: col<string | null>('provider_job_id'),
  providerReceipt: col<string | null>('provider_receipt'),
  assetHash: col<AssetHash | null>('asset_hash'),
  inputJson: col<string>('input_json'),
  outputJson: col<string>('output_json'),
  metadataJson: col<string>('metadata_json'),
  errorText: col<string | null>('error_text'),
  createdAt: col<number>('created_at'),
  submittedAt: col<number | null>('submitted_at'),
  submissionStartedAt: col<number | null>('submission_started_at'),
  cancelRequestedAt: col<number | null>('cancel_requested_at'),
  assetReadyAt: col<number | null>('asset_ready_at'),
  evaluatedAt: col<number | null>('evaluated_at'),
  completedAt: col<number | null>('completed_at'),
  updatedAt: col<number>('updated_at'),
});

export const TaskEvaluationsTable = defineTable('task_evaluations', {
  id: col<string>('id'),
  attemptId: col<string>('attempt_id'),
  taskListId: col<TaskListId>('task_list_id'),
  taskId: col<TaskId | null>('task_id'),
  kind: col<string>('kind'),
  canvasId: col<string>('canvas_id'),
  nodeId: col<string>('node_id'),
  artifactId: col<string>('artifact_id'),
  assetHash: col<AssetHash>('asset_hash'),
  mediaType: col<string>('media_type'),
  profile: col<string>('profile'),
  sourcePromptHash: col<string>('source_prompt_hash'),
  rubricVersion: col<string>('rubric_version'),
  evaluatorProviderId: col<string>('evaluator_provider_id'),
  evaluatorModel: col<string | null>('evaluator_model'),
  scoresJson: col<string>('scores_json'),
  total: col<number>('total'),
  verdict: col<string>('verdict'),
  strengthsJson: col<string>('strengths_json'),
  risksJson: col<string>('risks_json'),
  evidenceJson: col<string>('evidence_json'),
  repairDeltaJson: col<string | null>('repair_delta_json'),
  metadataJson: col<string>('metadata_json'),
  frameEvidenceJson: col<string>('frame_evidence_json'),
  createdAt: col<number>('created_at'),
});

export const TasksTable = defineTable('tasks', {
  id: col<TaskId>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  phaseKey: col<string>('phase_key'),
  phaseName: col<string>('phase_name'),
  phaseOrder: col<number>('phase_order'),
  taskKey: col<string>('task_key'),
  name: col<string>('name'),
  kind: col<string>('kind'),
  status: col<string>('status'),
  provider: col<string | null>('provider'),
  dependencyIdsJson: col<string>('dependency_ids_json'),
  attempts: col<number>('attempts'),
  maxRetries: col<number>('max_retries'),
  inputJson: col<string>('input_json'),
  outputJson: col<string>('output_json'),
  providerTaskId: col<string | null>('provider_task_id'),
  assetId: col<string | null>('asset_id'),
  errorText: col<string | null>('error_text'),
  progress: col<number>('progress'),
  currentStep: col<string | null>('current_step'),
  startedAt: col<number | null>('started_at'),
  completedAt: col<number | null>('completed_at'),
  updatedAt: col<number>('updated_at'),
});

export const TaskDependenciesTable = defineTable('task_dependencies', {
  taskId: col<TaskId>('task_id'),
  dependsOnTaskId: col<TaskId>('depends_on_task_id'),
});

export const TaskArtifactsTable = defineTable('task_artifacts', {
  id: col<string>('id'),
  taskListId: col<TaskListId>('task_list_id'),
  taskId: col<TaskId>('task_id'),
  attemptId: col<string | null>('attempt_id'),
  artifactType: col<string>('artifact_type'),
  entityType: col<string | null>('entity_type'),
  entityId: col<string | null>('entity_id'),
  assetHash: col<AssetHash | null>('asset_hash'),
  path: col<string | null>('path'),
  metadataJson: col<string>('metadata_json'),
  createdAt: col<number>('created_at'),
});
