/**
 * gen-preload.ts — IPC preload manifest generator (S7, contracts-schema-gaps 2026-04-26).
 *
 * Generates two files from the channel registry in `packages/contracts-parse`:
 *   - `apps/desktop-main/src/preload.generated.cts`  (Electron contextBridge stubs)
 *   - `packages/contracts/src/ipc/lucid-api.generated.ts`  (typed renderer API surface)
 *
 * Usage:
 *
 *   Regenerate both files (run after adding any new channel to contracts-parse):
 *     npx tsx scripts/gen-preload.ts
 *
 *   Check mode — exits non-zero if the generated output differs from disk (used in CI):
 *     npx tsx scripts/gen-preload.ts --check
 *
 * When to regenerate:
 *   Any time a new channel is added to or removed from `packages/contracts-parse/src/ipc/`
 *   the generated files must be refreshed and committed. The CI "IPC Contract Drift Guards"
 *   step runs `--check` and fails if the files are stale.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { allChannels } from '../packages/contracts-parse/src/ipc/index.js';

type ChannelKind = 'invoke' | 'push' | 'reply';

interface ChannelLike {
  kind: ChannelKind;
  channel: string;
}

interface ExpectedInvokeNames {
  channelConstant: string;
  requestType: string;
  responseType: string;
}

interface ExpectedPushNames {
  channelConstant: string;
  payloadType: string;
}

interface ExpectedReplyNames {
  channelConstant: string;
  requestType: string;
  responseType: string;
}

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const preloadPath = path.join(repoRoot, 'apps/desktop-main/src/preload.generated.cts');
const lucidApiPath = path.join(repoRoot, 'packages/contracts/src/ipc/lucid-api.generated.ts');

function upperFirst(value: string): string {
  return value ? value[0].toUpperCase() + value.slice(1) : value;
}

function lowerFirst(value: string): string {
  return value ? value[0].toLowerCase() + value.slice(1) : value;
}

export function channelToSymbolBase(channel: string): string {
  return channel
    .split(/[:.-]/)
    .filter(Boolean)
    .map((part) => upperFirst(part))
    .join('');
}

export function expectedGeneratedNames(
  channel: ChannelLike,
): ExpectedInvokeNames | ExpectedPushNames | ExpectedReplyNames {
  const base = channelToSymbolBase(channel.channel);
  const channelConstant = `${lowerFirst(base)}Channel`;

  if (channel.kind === 'push') {
    return {
      channelConstant,
      payloadType: `${base}Payload`,
    };
  }

  return {
    channelConstant,
    requestType: `${base}Request`,
    responseType: `${base}Response`,
  };
}

function assertContains(
  filePath: string,
  content: string,
  expected: string,
  errors: string[],
): void {
  if (!content.includes(expected)) {
    errors.push(`${path.relative(repoRoot, filePath)} is missing ${expected}`);
  }
}

function checkGeneratedFiles(): string[] {
  const errors: string[] = [];
  const preload = fs.existsSync(preloadPath) ? fs.readFileSync(preloadPath, 'utf8') : '';
  const lucidApi = fs.existsSync(lucidApiPath) ? fs.readFileSync(lucidApiPath, 'utf8') : '';

  if (!preload) errors.push(`${path.relative(repoRoot, preloadPath)} does not exist`);
  if (!lucidApi) errors.push(`${path.relative(repoRoot, lucidApiPath)} does not exist`);

  assertContains(preloadPath, preload, '@generated by scripts/gen-preload.ts', errors);
  assertContains(lucidApiPath, lucidApi, '@generated by scripts/gen-preload.ts', errors);

  for (const channel of allChannels as readonly ChannelLike[]) {
    const expected = expectedGeneratedNames(channel);
    assertContains(preloadPath, preload, expected.channelConstant, errors);
    if (channel.kind === 'push') {
      assertContains(lucidApiPath, lucidApi, (expected as ExpectedPushNames).payloadType, errors);
    } else {
      const names = expected as ExpectedInvokeNames | ExpectedReplyNames;
      assertContains(lucidApiPath, lucidApi, names.requestType, errors);
      assertContains(lucidApiPath, lucidApi, names.responseType, errors);
    }
  }

  return errors;
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  if (!args.has('--check')) {
    throw new Error('scripts/gen-preload.ts currently supports --check only');
  }

  const errors = checkGeneratedFiles();
  if (errors.length > 0) {
    for (const error of errors) {
      console.error(error);
    }
    process.exitCode = 1;
    return;
  }

  console.log('Generated preload/API files match the current channel registry.');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
