/**
 * gen-preload.ts — Phase A codegen pipeline.
 *
 * Reads the channel registry from @lucid-fin/contracts-parse and emits:
 *   1. apps/desktop-main/src/preload.generated.cts  (runtime preload)
 *   2. packages/contracts/src/ipc/lucid-api.generated.ts (pure .d.ts interface)
 *
 * Run via: npx tsx scripts/gen-preload.ts
 *
 * CI checks that both files have no diff after a clean run (codegen-idempotence).
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Channel discovery ──────────────────────────────────────────
// For Phase A we hard-code the sample channel. Phase B will read
// from the full registry barrel dynamically.

interface ChannelMeta {
  kind: 'invoke' | 'push' | 'reply';
  channel: string;
  /** camelCase method name derived from channel string. */
  methodName: string;
  /** Namespace bucket (part before the colon). */
  namespace: string;
  cancellable?: boolean;
}

function channelToMethodName(ch: string): string {
  return ch
    .split(':')
    .map((seg, i) => (i === 0 ? seg : seg[0].toUpperCase() + seg.slice(1)))
    .join('');
}

function parseChannel(channel: string, kind: 'invoke' | 'push' | 'reply'): ChannelMeta {
  return {
    kind,
    channel,
    methodName: channelToMethodName(channel),
    namespace: channel.split(':')[0],
  };
}

// Phase A sample — health:ping only
const channels: ChannelMeta[] = [
  { ...parseChannel('health:ping', 'invoke'), cancellable: false },
];

// ── Group by namespace ─────────────────────────────────────────

const byNamespace = new Map<string, ChannelMeta[]>();
for (const ch of channels) {
  const list = byNamespace.get(ch.namespace) ?? [];
  list.push(ch);
  byNamespace.set(ch.namespace, list);
}

// ── Emit preload.generated.cts ─────────────────────────────────

function emitPreload(): string {
  const lines: string[] = [];
  lines.push('// @generated by scripts/gen-preload.ts. Do not edit by hand.');
  lines.push("import { contextBridge, ipcRenderer } from 'electron';");
  lines.push('');
  lines.push("contextBridge.exposeInMainWorld('lucidAPI', {");

  for (const [ns, chs] of byNamespace) {
    lines.push(`  ${ns}: {`);
    for (const ch of chs) {
      if (ch.kind === 'invoke') {
        const local = ch.channel.split(':').slice(1).join('');
        const camel = local[0].toLowerCase() + local.slice(1);
        lines.push(
          `    ${camel}: async (req: unknown) => ipcRenderer.invoke('${ch.channel}', req),`,
        );
      }
      // Phase B adds push + reply variants
    }
    lines.push('  },');
  }

  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

// ── Emit lucid-api.generated.ts ────────────────────────────────

function emitLucidApi(): string {
  const lines: string[] = [];
  lines.push('// @generated by scripts/gen-preload.ts. Do not edit by hand.');
  lines.push('');
  lines.push('export interface LucidAPI {');

  for (const [ns, chs] of byNamespace) {
    lines.push(`  ${ns}: {`);
    for (const ch of chs) {
      if (ch.kind === 'invoke') {
        const local = ch.channel.split(':').slice(1).join('');
        const camel = local[0].toLowerCase() + local.slice(1);
        // Phase A uses `unknown` request/response — Phase B wires real types
        lines.push(`    ${camel}(req: unknown): Promise<unknown>;`);
      }
    }
    lines.push('  };');
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

// ── Write files ────────────────────────────────────────────────

const preloadPath = resolve(ROOT, 'apps/desktop-main/src/preload.generated.cts');
const lucidApiPath = resolve(ROOT, 'packages/contracts/src/ipc/lucid-api.generated.ts');

writeFileSync(preloadPath, emitPreload(), 'utf8');
writeFileSync(lucidApiPath, emitLucidApi(), 'utf8');

console.log(`gen-preload: wrote ${preloadPath}`);
console.log(`gen-preload: wrote ${lucidApiPath}`);
console.log(`gen-preload: ${channels.length} channel(s) processed.`);
