import { readFile, writeFile } from 'node:fs/promises';
import { registerHooks } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { format } from 'prettier';

export interface DesktopWireSource {
  readonly PUBLIC_WIRE_METHODS_V1: Readonly<Record<string, unknown>>;
  readonly LUCID_FIN_DESKTOP_API_GLOBAL_V1: string;
  readonly LUCID_FIN_WIRE_INVOKE_CHANNEL_V1: string;
  readonly LUCID_FIN_WIRE_PUSH_CHANNEL_V1: string;
  readonly LUCID_FIN_WINDOW_CONTROL_CHANNEL_V1: string;
}

export interface PreloadArtifacts {
  readonly preload: string;
  readonly rendererTypes: string;
}

type GenerationMode = 'check' | 'write';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contractsSourceRoot = resolve(repoRoot, 'packages/contracts/src');
const contractsSourceUrl = `${pathToFileURL(contractsSourceRoot).href}/`;
const wireSourcePath = resolve(contractsSourceRoot, 'wire.ts');
const preloadPath = resolve(repoRoot, 'apps/desktop-main/src/preload.cts');
const rendererTypesPath = resolve(contractsSourceRoot, 'desktop-api.generated.ts');
const prettierOptions = Object.freeze({
  parser: 'typescript',
  printWidth: 100,
  singleQuote: true,
  semi: true,
  trailingComma: 'all',
  endOfLine: 'lf',
} as const);

let sourceHookRegistered = false;

function registerContractsSourceHook(): void {
  if (sourceHookRegistered) return;
  registerHooks({
    resolve(specifier, context, nextResolve) {
      try {
        return nextResolve(specifier, context);
      } catch (cause) {
        if (specifier.endsWith('.js') && context.parentURL?.startsWith(contractsSourceUrl)) {
          return nextResolve(`${specifier.slice(0, -3)}.ts`, context);
        }
        throw cause;
      }
    },
  });
  sourceHookRegistered = true;
}

async function loadDesktopWireSource(): Promise<DesktopWireSource> {
  registerContractsSourceHook();
  return (await import(pathToFileURL(wireSourcePath).href)) as DesktopWireSource;
}

function upperFirst(value: string): string {
  return value.length === 0 ? value : `${value[0]!.toUpperCase()}${value.slice(1)}`;
}

function lowerFirst(value: string): string {
  return value.length === 0 ? value : `${value[0]!.toLowerCase()}${value.slice(1)}`;
}

interface PreparedMethod {
  readonly method: string;
  readonly namespace: string;
  readonly apiMethod: string;
}

function prepareMethods(methods: readonly string[]): readonly PreparedMethod[] {
  const seenMethods = new Set<string>();
  const prepared = methods.map((method) => {
    const [namespace, ...parts] = method.split('.');
    if (namespace === undefined || namespace.length === 0 || parts.length === 0) {
      throw new Error(`Desktop wire method must contain a namespace: ${method}`);
    }
    const apiMethod = lowerFirst(parts.map(upperFirst).join(''));
    const apiKey = `${namespace}.${apiMethod}`;
    if (seenMethods.has(apiKey)) {
      throw new Error(`Desktop wire methods produce a duplicate desktop API method: ${apiKey}`);
    }
    seenMethods.add(apiKey);
    return Object.freeze({ method, namespace, apiMethod });
  });
  return Object.freeze(prepared);
}

function groupMethods(
  methods: readonly PreparedMethod[],
): ReadonlyMap<string, readonly PreparedMethod[]> {
  const groups = new Map<string, PreparedMethod[]>();
  for (const method of methods) {
    const group = groups.get(method.namespace) ?? [];
    group.push(method);
    groups.set(method.namespace, group);
  }
  return groups;
}

function interfaceName(namespace: string): string {
  return `Desktop${upperFirst(namespace)}ApiV1`;
}

async function renderPreload(
  source: DesktopWireSource,
  methods: readonly PreparedMethod[],
): Promise<string> {
  const lines = [
    '// @generated by scripts/generate-preload.ts. Do not edit by hand.',
    "import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron';",
    '',
    `const INVOKE_CHANNEL = ${JSON.stringify(source.LUCID_FIN_WIRE_INVOKE_CHANNEL_V1)};`,
    `const PUSH_CHANNEL = ${JSON.stringify(source.LUCID_FIN_WIRE_PUSH_CHANNEL_V1)};`,
    `const WINDOW_CONTROL_CHANNEL = ${JSON.stringify(source.LUCID_FIN_WINDOW_CONTROL_CHANNEL_V1)};`,
    '',
    'interface DesktopCall {',
    '  readonly requestId: string;',
    '  readonly input: unknown;',
    '}',
    '',
    'function invoke(method: string, request: DesktopCall): Promise<unknown> {',
    '  return ipcRenderer.invoke(INVOKE_CHANNEL, {',
    '    wireVersion: 1,',
    "    kind: 'request',",
    '    requestId: request.requestId,',
    '    method,',
    '    input: request.input,',
    '  });',
    '}',
    '',
    'function onRunEventsAppended(callback: (push: unknown) => void): () => void {',
    '  const listener = (_event: IpcRendererEvent, push: unknown) => callback(push);',
    '  ipcRenderer.on(PUSH_CHANNEL, listener);',
    '  return () => ipcRenderer.removeListener(PUSH_CHANNEL, listener);',
    '}',
    '',
    "type WindowControlAction = 'minimize' | 'toggleMaximize' | 'close';",
    '',
    'function windowControl(action: WindowControlAction): void {',
    '  ipcRenderer.send(WINDOW_CONTROL_CHANNEL, action);',
    '}',
    '',
    `contextBridge.exposeInMainWorld(${JSON.stringify(source.LUCID_FIN_DESKTOP_API_GLOBAL_V1)}, {`,
  ];

  for (const [namespace, group] of groupMethods(methods)) {
    lines.push(`  ${namespace}: {`);
    for (const method of group) {
      lines.push(`    ${method.apiMethod}: (request: DesktopCall) =>`);
      lines.push(`      invoke(${JSON.stringify(method.method)}, request),`);
    }
    if (namespace === 'run') lines.push('    onEventsAppended: onRunEventsAppended,');
    lines.push('  },');
  }
  lines.push('  windowControls: {');
  lines.push("    minimize: () => windowControl('minimize'),");
  lines.push("    toggleMaximize: () => windowControl('toggleMaximize'),");
  lines.push("    close: () => windowControl('close'),");
  lines.push('  },');
  lines.push('});', '');
  return format(lines.join('\n'), prettierOptions);
}

async function renderRendererTypes(methods: readonly PreparedMethod[]): Promise<string> {
  const lines = [
    '// @generated by scripts/generate-preload.ts. Do not edit by hand.',
    '',
    'import type {',
    '  PublicWireMethodV1,',
    '  WireFailureV1,',
    '  WirePushV1,',
    '  WireRequestV1,',
    '  WireSuccessV1,',
    "} from './wire.js';",
    '',
    'export type DesktopCallV1<Method extends PublicWireMethodV1> = Pick<',
    '  Extract<WireRequestV1, { readonly method: Method }>,',
    "  'requestId' | 'input'",
    '>;',
    '',
    'export type DesktopResponseV1<Method extends PublicWireMethodV1> =',
    '  | Extract<WireSuccessV1, { readonly method: Method }>',
    "  | (Omit<WireFailureV1, 'method'> & { readonly method: Method });",
    '',
  ];

  for (const [namespace, group] of groupMethods(methods)) {
    lines.push(`export interface ${interfaceName(namespace)} {`);
    for (const method of group) {
      lines.push(`  ${method.apiMethod}(`);
      lines.push(`    request: DesktopCallV1<${JSON.stringify(method.method)}>,`);
      lines.push(`  ): Promise<DesktopResponseV1<${JSON.stringify(method.method)}>>;`);
    }
    if (namespace === 'run') {
      lines.push('  onEventsAppended(callback: (push: WirePushV1) => void): () => void;');
    }
    lines.push('}', '');
  }

  lines.push('export interface DesktopWindowControlsApiV1 {');
  lines.push('  minimize(): void;');
  lines.push('  toggleMaximize(): void;');
  lines.push('  close(): void;');
  lines.push('}', '');

  lines.push('export interface DesktopApiV1 {');
  for (const namespace of groupMethods(methods).keys()) {
    lines.push(`  readonly ${namespace}: ${interfaceName(namespace)};`);
  }
  lines.push('  readonly windowControls: DesktopWindowControlsApiV1;');
  lines.push('}', '');
  return format(lines.join('\n'), prettierOptions);
}

export async function buildPreloadArtifacts(
  sourceValue?: DesktopWireSource,
): Promise<PreloadArtifacts> {
  const source = sourceValue ?? (await loadDesktopWireSource());
  const methods = prepareMethods(Object.keys(source.PUBLIC_WIRE_METHODS_V1));
  if (methods.length === 0) throw new Error('Desktop wire method registry is empty');
  return Object.freeze({
    preload: await renderPreload(source, methods),
    rendererTypes: await renderRendererTypes(methods),
  });
}

export async function generatePreload(
  mode: GenerationMode,
  source?: DesktopWireSource,
): Promise<void> {
  const artifacts = await buildPreloadArtifacts(source);
  for (const [path, expected] of [
    [preloadPath, artifacts.preload],
    [rendererTypesPath, artifacts.rendererTypes],
  ] as const) {
    if (mode === 'write') {
      await writeFile(path, expected, 'utf8');
      continue;
    }
    const actual = await readFile(path, 'utf8').catch(() => undefined);
    if (actual !== expected) throw new Error(`Generated preload drift: ${path}`);
  }
}

async function main(): Promise<void> {
  const flag = process.argv[2];
  if (flag !== '--write' && flag !== '--check') {
    throw new Error('Usage: tsx scripts/generate-preload.ts --write|--check');
  }
  await generatePreload(flag === '--write' ? 'write' : 'check');
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
