// @generated by scripts/generate-target-preload.ts. Do not edit by hand.

import type {
  PublicWireMethodV1,
  WireFailureV1,
  WirePushV1,
  WireRequestV1,
  WireSuccessV1,
} from './wire.js';

export type TargetDesktopCallV1<Method extends PublicWireMethodV1> = Pick<
  Extract<WireRequestV1, { readonly method: Method }>,
  'requestId' | 'input'
>;

export type TargetDesktopResponseV1<Method extends PublicWireMethodV1> =
  | Extract<WireSuccessV1, { readonly method: Method }>
  | (Omit<WireFailureV1, 'method'> & { readonly method: Method });

export interface TargetDesktopCanvasApiV1 {
  apply(
    request: TargetDesktopCallV1<'canvas.apply'>,
  ): Promise<TargetDesktopResponseV1<'canvas.apply'>>;
  get(request: TargetDesktopCallV1<'canvas.get'>): Promise<TargetDesktopResponseV1<'canvas.get'>>;
}

export interface TargetDesktopChatApiV1 {
  archive(
    request: TargetDesktopCallV1<'chat.archive'>,
  ): Promise<TargetDesktopResponseV1<'chat.archive'>>;
  create(
    request: TargetDesktopCallV1<'chat.create'>,
  ): Promise<TargetDesktopResponseV1<'chat.create'>>;
  delete(
    request: TargetDesktopCallV1<'chat.delete'>,
  ): Promise<TargetDesktopResponseV1<'chat.delete'>>;
  list(request: TargetDesktopCallV1<'chat.list'>): Promise<TargetDesktopResponseV1<'chat.list'>>;
  rename(
    request: TargetDesktopCallV1<'chat.rename'>,
  ): Promise<TargetDesktopResponseV1<'chat.rename'>>;
}

export interface TargetDesktopConfirmationApiV1 {
  respond(
    request: TargetDesktopCallV1<'confirmation.respond'>,
  ): Promise<TargetDesktopResponseV1<'confirmation.respond'>>;
}

export interface TargetDesktopDecisionApiV1 {
  protect(
    request: TargetDesktopCallV1<'decision.protect'>,
  ): Promise<TargetDesktopResponseV1<'decision.protect'>>;
  record(
    request: TargetDesktopCallV1<'decision.record'>,
  ): Promise<TargetDesktopResponseV1<'decision.record'>>;
}

export interface TargetDesktopDeliveryApiV1 {
  apply(
    request: TargetDesktopCallV1<'delivery.apply'>,
  ): Promise<TargetDesktopResponseV1<'delivery.apply'>>;
  query(
    request: TargetDesktopCallV1<'delivery.query'>,
  ): Promise<TargetDesktopResponseV1<'delivery.query'>>;
}

export interface TargetDesktopHistoryApiV1 {
  query(
    request: TargetDesktopCallV1<'history.query'>,
  ): Promise<TargetDesktopResponseV1<'history.query'>>;
}

export interface TargetDesktopInteractionApiV1 {
  answer(
    request: TargetDesktopCallV1<'interaction.answer'>,
  ): Promise<TargetDesktopResponseV1<'interaction.answer'>>;
}

export interface TargetDesktopMediaApiV1 {
  globalImport(
    request: TargetDesktopCallV1<'media.global.import'>,
  ): Promise<TargetDesktopResponseV1<'media.global.import'>>;
  globalList(
    request: TargetDesktopCallV1<'media.global.list'>,
  ): Promise<TargetDesktopResponseV1<'media.global.list'>>;
  globalRemove(
    request: TargetDesktopCallV1<'media.global.remove'>,
  ): Promise<TargetDesktopResponseV1<'media.global.remove'>>;
  projectAttach(
    request: TargetDesktopCallV1<'media.project.attach'>,
  ): Promise<TargetDesktopResponseV1<'media.project.attach'>>;
  projectDetach(
    request: TargetDesktopCallV1<'media.project.detach'>,
  ): Promise<TargetDesktopResponseV1<'media.project.detach'>>;
  projectLink(
    request: TargetDesktopCallV1<'media.project.link'>,
  ): Promise<TargetDesktopResponseV1<'media.project.link'>>;
  projectList(
    request: TargetDesktopCallV1<'media.project.list'>,
  ): Promise<TargetDesktopResponseV1<'media.project.list'>>;
  previewIssue(
    request: TargetDesktopCallV1<'media.preview.issue'>,
  ): Promise<TargetDesktopResponseV1<'media.preview.issue'>>;
}

export interface TargetDesktopMessageApiV1 {
  list(
    request: TargetDesktopCallV1<'message.list'>,
  ): Promise<TargetDesktopResponseV1<'message.list'>>;
  send(
    request: TargetDesktopCallV1<'message.send'>,
  ): Promise<TargetDesktopResponseV1<'message.send'>>;
}

export interface TargetDesktopOperationApiV1 {
  cancel(
    request: TargetDesktopCallV1<'operation.cancel'>,
  ): Promise<TargetDesktopResponseV1<'operation.cancel'>>;
  get(
    request: TargetDesktopCallV1<'operation.get'>,
  ): Promise<TargetDesktopResponseV1<'operation.get'>>;
}

export interface TargetDesktopOsApiV1 {
  exportPick(
    request: TargetDesktopCallV1<'os.export.pick'>,
  ): Promise<TargetDesktopResponseV1<'os.export.pick'>>;
  mediaPick(
    request: TargetDesktopCallV1<'os.media.pick'>,
  ): Promise<TargetDesktopResponseV1<'os.media.pick'>>;
}

export interface TargetDesktopOverviewApiV1 {
  get(
    request: TargetDesktopCallV1<'overview.get'>,
  ): Promise<TargetDesktopResponseV1<'overview.get'>>;
}

export interface TargetDesktopPluginApiV1 {
  apply(
    request: TargetDesktopCallV1<'plugin.apply'>,
  ): Promise<TargetDesktopResponseV1<'plugin.apply'>>;
  query(
    request: TargetDesktopCallV1<'plugin.query'>,
  ): Promise<TargetDesktopResponseV1<'plugin.query'>>;
}

export interface TargetDesktopProductionApiV1 {
  apply(
    request: TargetDesktopCallV1<'production.apply'>,
  ): Promise<TargetDesktopResponseV1<'production.apply'>>;
  query(
    request: TargetDesktopCallV1<'production.query'>,
  ): Promise<TargetDesktopResponseV1<'production.query'>>;
}

export interface TargetDesktopProjectApiV1 {
  capabilitiesGet(
    request: TargetDesktopCallV1<'project.capabilities.get'>,
  ): Promise<TargetDesktopResponseV1<'project.capabilities.get'>>;
  create(
    request: TargetDesktopCallV1<'project.create'>,
  ): Promise<TargetDesktopResponseV1<'project.create'>>;
  get(request: TargetDesktopCallV1<'project.get'>): Promise<TargetDesktopResponseV1<'project.get'>>;
  list(
    request: TargetDesktopCallV1<'project.list'>,
  ): Promise<TargetDesktopResponseV1<'project.list'>>;
  settingsGet(
    request: TargetDesktopCallV1<'project.settings.get'>,
  ): Promise<TargetDesktopResponseV1<'project.settings.get'>>;
  settingsUpdate(
    request: TargetDesktopCallV1<'project.settings.update'>,
  ): Promise<TargetDesktopResponseV1<'project.settings.update'>>;
  update(
    request: TargetDesktopCallV1<'project.update'>,
  ): Promise<TargetDesktopResponseV1<'project.update'>>;
}

export interface TargetDesktopResultApiV1 {
  query(
    request: TargetDesktopCallV1<'result.query'>,
  ): Promise<TargetDesktopResponseV1<'result.query'>>;
}

export interface TargetDesktopRunApiV1 {
  control(
    request: TargetDesktopCallV1<'run.control'>,
  ): Promise<TargetDesktopResponseV1<'run.control'>>;
  eventsList(
    request: TargetDesktopCallV1<'run.events.list'>,
  ): Promise<TargetDesktopResponseV1<'run.events.list'>>;
  get(request: TargetDesktopCallV1<'run.get'>): Promise<TargetDesktopResponseV1<'run.get'>>;
  sendFollowup(
    request: TargetDesktopCallV1<'run.sendFollowup'>,
  ): Promise<TargetDesktopResponseV1<'run.sendFollowup'>>;
  onEventsAppended(callback: (push: WirePushV1) => void): () => void;
}

export interface TargetDesktopApiV1 {
  readonly canvas: TargetDesktopCanvasApiV1;
  readonly chat: TargetDesktopChatApiV1;
  readonly confirmation: TargetDesktopConfirmationApiV1;
  readonly decision: TargetDesktopDecisionApiV1;
  readonly delivery: TargetDesktopDeliveryApiV1;
  readonly history: TargetDesktopHistoryApiV1;
  readonly interaction: TargetDesktopInteractionApiV1;
  readonly media: TargetDesktopMediaApiV1;
  readonly message: TargetDesktopMessageApiV1;
  readonly operation: TargetDesktopOperationApiV1;
  readonly os: TargetDesktopOsApiV1;
  readonly overview: TargetDesktopOverviewApiV1;
  readonly plugin: TargetDesktopPluginApiV1;
  readonly production: TargetDesktopProductionApiV1;
  readonly project: TargetDesktopProjectApiV1;
  readonly result: TargetDesktopResultApiV1;
  readonly run: TargetDesktopRunApiV1;
}
