import type { LegacySourceExpectedSchemas } from './source-preflight.js';

export const I0_LEGACY_SOURCE_SCHEMAS: LegacySourceExpectedSchemas = {
  main: {
    tables: [
      {
        name: 'asset_contents',
        kind: 'table',
        columns: [
          'created_at',
          'duration',
          'file_size',
          'format',
          'generation_metadata',
          'has_audio',
          'hash',
          'height',
          'prompt',
          'provider',
          'type',
          'width',
        ],
      },
      {
        name: 'asset_entries',
        kind: 'table',
        columns: ['asset_hash', 'created_at', 'display_name', 'folder_id', 'id', 'tags'],
      },
      {
        name: 'asset_folders',
        kind: 'table',
        columns: ['created_at', 'id', 'name', 'parent_id', 'sort_order', 'updated_at'],
      },
      {
        name: 'canvas_edges',
        kind: 'table',
        columns: [
          'auto_label',
          'canvas_id',
          'created_at',
          'id',
          'label',
          'source',
          'source_handle',
          'status',
          'target',
          'target_handle',
          'updated_at',
          'z_index',
        ],
      },
      {
        name: 'canvas_nodes',
        kind: 'table',
        columns: [
          'canvas_id',
          'created_at',
          'data_json',
          'height',
          'id',
          'position_x',
          'position_y',
          'type',
          'updated_at',
          'width',
          'z_index',
        ],
      },
      {
        name: 'canvases',
        kind: 'table',
        columns: [
          'archived_at',
          'aspect_ratio',
          'audio_provider_id',
          'created_at',
          'default_height',
          'default_width',
          'delivery_sequence_json',
          'delivery_sequence_revision',
          'id',
          'image_provider_id',
          'llm_provider_id',
          'name',
          'negative_prompt',
          'notes',
          'publish_height',
          'publish_video_height',
          'publish_video_width',
          'publish_width',
          'resolution_policy_json',
          'style_plate',
          'updated_at',
          'video_provider_id',
          'viewport',
          'visual_style_policy_json',
        ],
      },
      {
        name: 'character_folders',
        kind: 'table',
        columns: ['created_at', 'id', 'name', 'parent_id', 'sort_order', 'updated_at'],
      },
      {
        name: 'characters',
        kind: 'table',
        columns: [
          'age',
          'appearance',
          'body',
          'costumes',
          'created_at',
          'default_loadout_id',
          'deleted_at',
          'description',
          'distinct_traits',
          'face',
          'folder_id',
          'gender',
          'hair',
          'id',
          'loadouts',
          'name',
          'personality',
          'ref_image',
          'reference_images',
          'role',
          'skin_tone',
          'tags',
          'updated_at',
          'vocal_traits',
          'voice',
        ],
      },
      {
        name: 'color_styles',
        kind: 'table',
        columns: [
          'created_at',
          'exposure',
          'gradients',
          'id',
          'name',
          'palette',
          'source_asset',
          'source_type',
          'tags',
          'updated_at',
        ],
      },
      {
        name: 'commander_events',
        kind: 'table',
        columns: [
          'emitted_at',
          'kind',
          'payload',
          'private_payload',
          'run_id',
          'seq',
          'session_id',
          'step',
        ],
      },
      {
        name: 'commander_run_attachments',
        kind: 'table',
        columns: ['content_hash', 'mime_type', 'ordinal', 'original_name', 'role', 'run_id'],
      },
      {
        name: 'commander_run_canvases',
        kind: 'table',
        columns: ['canvas_id', 'ordinal', 'released_at', 'run_id'],
      },
      {
        name: 'commander_runs',
        kind: 'table',
        columns: [
          'accepted_at',
          'completed_at',
          'default_canvas_id',
          'display_name',
          'error_text',
          'id',
          'intent',
          'last_seq',
          'objective',
          'parent_run_id',
          'retry_of_run_id',
          'session_id',
          'started_at',
          'status',
          'work_type',
        ],
      },
      {
        name: 'commander_sessions',
        kind: 'table',
        columns: [
          'context_graph_json',
          'created_at',
          'default_canvas_id',
          'id',
          'messages',
          'title',
          'updated_at',
        ],
      },
      {
        name: 'custom_shot_templates',
        kind: 'table',
        columns: ['created_at', 'description', 'id', 'name', 'tracks_json', 'updated_at'],
      },
      {
        name: 'delivery_asset_refs',
        kind: 'table',
        columns: ['asset_hash', 'canvas_id'],
      },
      {
        name: 'dependencies',
        kind: 'table',
        columns: ['source_id', 'source_type', 'target_id', 'target_type'],
      },
      {
        name: 'equipment',
        kind: 'table',
        columns: [
          'color',
          'condition',
          'created_at',
          'deleted_at',
          'description',
          'folder_id',
          'function_desc',
          'id',
          'material',
          'name',
          'reference_images',
          'subtype',
          'tags',
          'type',
          'updated_at',
          'visual_details',
        ],
      },
      {
        name: 'equipment_folders',
        kind: 'table',
        columns: ['created_at', 'id', 'name', 'parent_id', 'sort_order', 'updated_at'],
      },
      {
        name: 'location_folders',
        kind: 'table',
        columns: ['created_at', 'id', 'name', 'parent_id', 'sort_order', 'updated_at'],
      },
      {
        name: 'locations',
        kind: 'table',
        columns: [
          'architecture_style',
          'atmosphere_keywords',
          'created_at',
          'deleted_at',
          'description',
          'dominant_colors',
          'folder_id',
          'id',
          'key_features',
          'lighting',
          'mood',
          'name',
          'reference_images',
          'sub_location',
          'tags',
          'time_of_day',
          'type',
          'updated_at',
          'weather',
        ],
      },
      {
        name: 'plan_approvals',
        kind: 'table',
        columns: [
          'created_at',
          'decided_at',
          'gate_key',
          'id',
          'manifest_hash',
          'resume_token_hash',
          'status',
          'subject_hash',
          'subject_logical_key',
          'subject_revision',
          'task_list_id',
          'updated_at',
        ],
      },
      {
        name: 'plan_documents',
        kind: 'table',
        columns: [
          'content_hash',
          'content_json',
          'created_at',
          'document_type',
          'id',
          'logical_key',
          'revision',
          'schema_version',
          'status',
          'task_list_id',
          'updated_at',
        ],
      },
      {
        name: 'preset_overrides',
        kind: 'table',
        columns: [
          'category',
          'created_at',
          'defaults',
          'description',
          'id',
          'is_user',
          'name',
          'params',
          'preset_id',
          'prompt',
          'updated_at',
        ],
      },
      {
        name: 'project_settings',
        kind: 'table',
        columns: ['key', 'updated_at', 'value'],
      },
      {
        name: 'prompt_assemblies',
        kind: 'table',
        columns: [
          'assembled_at',
          'authority_json',
          'canvas_id',
          'conditioning_manifest_json',
          'created_at',
          'error_text',
          'host_constraints_json',
          'id',
          'input_hash',
          'input_json',
          'llm_model',
          'llm_provider_id',
          'media_type',
          'mode',
          'node_id',
          'node_updated_at',
          'output_json',
          'parent_assembly_id',
          'provider_profile_json',
          'purpose',
          'row_version',
          'source_asset_hash',
          'source_attempt_id',
          'source_evaluation_id',
          'sources_json',
          'status',
          'submitted_at',
          'task_id',
          'task_list_id',
          'terminal_at',
          'updated_at',
        ],
      },
      {
        name: 'scripts',
        kind: 'table',
        columns: ['content', 'created_at', 'format', 'id', 'parsed_scenes', 'updated_at'],
      },
      {
        name: 'snapshots',
        kind: 'table',
        columns: ['created_at', 'data', 'id', 'label', 'schema_version', 'session_id', 'trigger'],
      },
      {
        name: 'task_artifacts',
        kind: 'table',
        columns: [
          'artifact_type',
          'asset_hash',
          'attempt_id',
          'created_at',
          'entity_id',
          'entity_type',
          'id',
          'metadata_json',
          'path',
          'task_id',
          'task_list_id',
        ],
      },
      {
        name: 'task_attempts',
        kind: 'table',
        columns: [
          'asset_hash',
          'asset_ready_at',
          'attempt',
          'cancel_requested_at',
          'canvas_id',
          'completed_at',
          'created_at',
          'destination_path',
          'error_text',
          'estimated_cost_usd',
          'evaluated_at',
          'file_count',
          'generation_spec_json',
          'id',
          'idempotency_key',
          'input_json',
          'kind',
          'manifest_hash',
          'manifest_revision',
          'media_type',
          'metadata_json',
          'model',
          'negative_prompt',
          'node_id',
          'output_json',
          'package_bytes',
          'package_hash',
          'parent_attempt_id',
          'prompt',
          'prompt_hash',
          'provider_id',
          'provider_job_id',
          'provider_receipt',
          'repair_delta_json',
          'reported_actual_cost_usd',
          'row_version',
          'scope',
          'seed',
          'spec_hash',
          'staging_path',
          'status',
          'submission_purpose',
          'submission_started_at',
          'submitted_at',
          'task_id',
          'task_list_id',
          'updated_at',
        ],
      },
      {
        name: 'task_decisions',
        kind: 'table',
        columns: [
          'allow_free_text',
          'answer',
          'answered_at',
          'canvas_id',
          'created_at',
          'decision_key',
          'id',
          'options_json',
          'question',
          'question_id',
          'row_version',
          'selected_option_id',
          'status',
          'subject_revision',
          'task_id',
          'task_list_id',
          'updated_at',
        ],
      },
      {
        name: 'task_dependencies',
        kind: 'table',
        columns: ['depends_on_task_id', 'task_id'],
      },
      {
        name: 'task_evaluations',
        kind: 'table',
        columns: [
          'artifact_id',
          'asset_hash',
          'attempt_id',
          'canvas_id',
          'created_at',
          'evaluator_model',
          'evaluator_provider_id',
          'evidence_json',
          'frame_evidence_json',
          'id',
          'kind',
          'media_type',
          'metadata_json',
          'node_id',
          'profile',
          'repair_delta_json',
          'risks_json',
          'rubric_version',
          'scores_json',
          'source_prompt_hash',
          'strengths_json',
          'task_id',
          'task_list_id',
          'total',
          'verdict',
        ],
      },
      {
        name: 'task_events',
        kind: 'table',
        columns: [
          'actor',
          'causation_id',
          'correlation_id',
          'event_id',
          'event_timestamp',
          'payload_json',
          'seq',
          'task_list_id',
        ],
      },
      {
        name: 'task_lists',
        kind: 'table',
        columns: [
          'completed_at',
          'completed_phases',
          'completed_tasks',
          'created_at',
          'current_gate',
          'current_phase_key',
          'current_task_id',
          'definition_version',
          'engine_version',
          'entity_id',
          'entity_type',
          'error_text',
          'heartbeat_at',
          'id',
          'input_json',
          'lease_expires_at',
          'lease_owner',
          'lease_token',
          'metadata_json',
          'output_json',
          'progress',
          'row_version',
          'started_at',
          'status',
          'summary',
          'task_list_type',
          'total_phases',
          'total_tasks',
          'trigger_source',
          'updated_at',
        ],
      },
      {
        name: 'tasks',
        kind: 'table',
        columns: [
          'asset_id',
          'attempts',
          'completed_at',
          'current_step',
          'dependency_ids_json',
          'error_text',
          'id',
          'input_json',
          'kind',
          'max_retries',
          'name',
          'output_json',
          'phase_key',
          'phase_name',
          'phase_order',
          'progress',
          'provider',
          'provider_task_id',
          'started_at',
          'status',
          'task_key',
          'task_list_id',
          'updated_at',
        ],
      },
      {
        name: 'asset_entries_fts',
        kind: 'virtual',
        columns: ['display_name', 'entry_id', 'prompt', 'tags'],
      },
    ],
  },
  prompts: {
    tables: [
      {
        name: 'process_prompts',
        kind: 'table',
        columns: [
          'created_at',
          'custom_value',
          'default_value',
          'description',
          'id',
          'name',
          'process_key',
          'updated_at',
        ],
      },
      {
        name: 't_prompt_overrides',
        kind: 'table',
        columns: ['code', 'customValue'],
      },
    ],
  },
};
