// Re-export from @lucid-fin/task-execution
export {
  TaskListRegistry,
  TaskListPlanner,
  TaskExecutionEngine,
  registerDefaultTaskLists,
  styleExtractTaskList,
  audioProductionTaskList,
  movieProductionTaskList,
  createMovieProductionTaskListGraph,
  getMovieProductionTaskContract,
  type TaskExecutionContext,
  type TaskExecutionResult,
  type TaskHandler,
  type TaskProjectionFields,
  type RegisteredTaskListBlueprint,
  type RegisteredTaskBlueprint,
  type PlannedTaskListRows,
  type TaskListPlanRequest,
  type TaskExecutionEngineOptions,
  type ProductionPlanCreateRequest,
  type ProductionPlanCreateResult,
  type ProductionPlanRevisionRequest,
  type TaskListCommanderContinuationConfig,
  type TaskListCommanderContinuationClaim,
  type ClaimCommanderContinuationResult,
  type ContextCheckpointCreateResult,
  type ProductionMediaTaskContext,
  type CreativeTaskCompletionRequest,
  type ProductionMediaTaskCompletionRequest,
  type ProductionMediaFeedbackReservationRequest,
  type ExternalTaskCompletionResult,
  type VisualAuditionStartRequest,
  type VisualAuditionStartResult,
  type VisualAuditionSnapshotRequest,
  type VisualConstitutionSelectionResult,
  VISUAL_PREVIEW_RUBRIC_VERSION,
  type TaskListStartRequest,
  type MovieProductionTaskListGraph,
  type MovieProductionTaskContract,
  type MovieProductionTaskRole,
  type ProductionGraphShot,
} from '@lucid-fin/task-execution';

// Re-export from @lucid-fin/agent
export {
  ToolRegistry,
  TOOL_PROGRAM_LIMITS,
  createToolProgramTool,
  describeToolProgram,
  executeToolProgram,
  parseToolProgram,
  ToolProgramBlockedError,
  ToolProgramCancelledError,
  PROJECTOR_VERSION,
  canonicalJson,
  hashCommanderContextProjection,
  hashEventChain,
  projectCommanderContext,
  registerToolModule,
  AgentOrchestrator,
  createAgentOrchestratorForRun,
  contractRegistry,
  decide,
  freshRunId,
  coercePhaseNoteCode,
  inferErrorCodeFromMessage,
  ContextManager,
  SCRATCHPAD_MAX_CHARS,
  createEmptyScratchpad,
  serializeScratchpad,
  makeStampedEmit,
  RunResourceBudgetController,
  parseRunResourceBudgetCheckpoint,
  registerAgentTools,
  registerFiltered,
  EXCLUDED_TOOLS,
  createCanvasTools,
  createEntityTools,
  createScriptTools,
  createColorStyleTools,
  colorStyleToolModule,
  createAssetTools,
  createPromptTools,
  createPresetTools,
  createTaskListTools,
  createMetaTools,
  createTextAnalyzeTools,
  createSnapshotTools,
  snapshotToolModule,
  createRunChecklistTools,
  RunChecklistStore,
  RunChecklistStoreError,
  ok,
  fail,
  requireString,
  requireNumber,
  requireStringArray,
  requireText,
  requireBoolean,
  deriveCanvasSyncMutatingToolNames,
  deriveEntityMutatingToolNames,
  createProviderTools,
  type ContextReplayMode,
  type PublicContextProjection,
  type PublicToolProjection,
  type ToolCategory,
  type ToolDefinition,
  type ToolExecutionContext,
  type ToolResult,
  type ToolProgram,
  type ToolProgramAggregate,
  type ToolProgramCall,
  type ToolProgramChildCall,
  type ToolProgramChildResult,
  type ToolProgramHost,
  type ToolProgramIdentity,
  type ToolProgramChildLifecycle,
  type ToolProgramChildLifecycleFactory,
  type ToolProgramChildLifecycleRequest,
  type ToolProgramChildOutcome,
  type TaskDecisionPersistenceRequest,
  type TaskDecisionPersistenceResult,
  type ToolProgramPath,
  type ToolProgramStep,
  type ToolProgramValueRef,
  type AgentPermissionMode,
  type SubagentSpawnRequest,
  type SubagentToolHost,
  type SubagentToolHostFactory,
  type SubagentToolHostFactoryRequest,
  type EventContextProjectionInput,
  type EventContextProjectionRun,
  type EventContextRunHead,
  type ToolModule,
  type AgentContext,
  type AgentOptions,
  type AgentExecutionOptions,
  type AgentRecoveryState,
  type AgentLLMRequestDiagnostics,
  type AgentPersistentContextProjection,
  type ContextRecoveryReport,
  type ContextRecoveryReportResult,
  type AgentStreamEvent,
  type HistoryEntry,
  type StampedStreamEvent,
  type StampedStreamEmission,
  type StampedStreamSink,
  type StreamEmit,
  type OrchestratorFactoryInput,
  type OrchestratorVariant,
  type RunIntent,
  type CompletionContract,
  type CompletionEvidence,
  type ExitDecision,
  type BlockerReason,
  type ReadonlyCompletionEvidenceList,
  type CommitRequirement,
  type SuccessSignal,
  type ExitOutcomeKind,
  type ContextCompactionResult,
  type RunContext,
  type ResourceQuote,
  type ResourceMeasurement,
  type ResourceStateSnapshot,
  type ResourceReservation,
  type RunResourceClockCheckpoint,
  type RunResourceLeaseCheckpoint,
  type RunResourceOperationCheckpoint,
  type RunResourceBudgetCheckpoint,
  type RunResourceBudgetRestore,
  type Scratchpad,
  type AllToolDeps,
  type CanvasToolDeps,
  type EntityToolDeps,
  type ScriptToolDeps,
  type ColorStyleToolDeps,
  type ProviderToolDeps,
  type ProviderInfo,
  type AssetToolDeps,
  type PromptToolDeps,
  type PromptDetail,
  type PromptListEntry,
  type PresetToolDeps,
  type TaskListToolDeps,
  type PrepareAudioTaskInput,
  type SubmitAudioPromptInput,
  type CreateVisualAuditionsInput,
  type CreateVisualAuditionsResult,
  type ProduceTaskMediaInput,
  type RefineTaskMediaInput,
  type PromptGuide,
  type MetaToolDeps,
  type CopywritingToolDeps,
  type VisionToolDeps,
  type TextAnalyzeToolDeps,
  type SnapshotToolDeps,
  type RunChecklistSnapshot,
  type RunChecklistItem,
  type RunChecklistItemStatus,
  type RunChecklistStoreOptions,
  type RunChecklistSetInput,
  type RunChecklistUpdateInput,
  type TaskListToolPolicy,
  type TaskListToolPolicyPhase,
} from '@lucid-fin/agent';

// Own exports (retained in this package)
export { LRUCache, type LRUCacheOptions } from './lru-cache.js';
export {
  compilePrompt,
  computeEffectiveIntensity,
  getCameraShot,
  resolvePromptTemplate,
  type CameraShot,
  type CompiledPrompt,
  type PromptCompilerInput,
  type PromptReferenceBinding,
  type PromptMode,
  type ResolvedCharacter,
} from './prompt-compiler.js';
export { TemplateManager, type SceneTemplate } from './template-manager.js';
export {
  getToolCompactionCategory,
  getClassifiedToolNames,
  type ToolCompactionCategory,
} from '@lucid-fin/shared-utils';
