// Re-export from @lucid-fin/workflows
export {
  WorkflowRegistry,
  WorkflowPlanner,
  WorkflowEngine,
  WorkflowRecovery,
  registerDefaultWorkflows,
  styleExtractWorkflow,
  characterGenerateReferencesWorkflow,
  locationGenerateReferencesWorkflow,
  type WorkflowTaskExecutionContext,
  type WorkflowTaskExecutionResult,
  type WorkflowTaskHandler,
  type WorkflowProjectionFields,
  type RegisteredWorkflowDefinition,
  type RegisteredWorkflowStageDefinition,
  type RegisteredWorkflowTaskDefinition,
  type PlannedWorkflowRows,
  type WorkflowPlanRequest,
  type WorkflowTaskDependencyRow,
  type WorkflowEngineOptions,
  type ProductionPlanCreateRequest,
  type ProductionPlanCreateResult,
  type ContextCheckpointCreateResult,
  type ProductionMediaWorkflowContext,
  type VisualAuditionStartRequest,
  type VisualAuditionStartResult,
  type VisualAuditionSnapshotRequest,
  type VisualConstitutionSelectionResult,
  VISUAL_PREVIEW_RUBRIC_VERSION,
  type WorkflowStartRequest,
} from '@lucid-fin/workflows';

// Re-export from @lucid-fin/agent
export {
  buildCharacterAppearancePrompt,
  buildCharacterRefImagePrompt,
  buildLocationRefImagePrompt,
  AgentToolRegistry,
  registerToolModule,
  AgentOrchestrator,
  createAgentOrchestratorForRun,
  contractRegistry,
  decide,
  classifyIntent,
  evaluateProcessPromptSpecs,
  createStylePlateLockSpec,
  freshRunId,
  coercePhaseNoteCode,
  inferErrorCodeFromMessage,
  ContextManager,
  selectContextualToolSet,
  SCRATCHPAD_MAX_CHARS,
  createEmptyScratchpad,
  serializeScratchpad,
  registerAgentTools,
  registerFiltered,
  EXCLUDED_TOOLS,
  createCanvasTools,
  createEntityTools,
  createScriptTools,
  createJobTools,
  jobToolModule,
  createSeriesTools,
  seriesToolModule,
  createColorStyleTools,
  colorStyleToolModule,
  createAssetTools,
  createPromptTools,
  createRenderTools,
  createPresetTools,
  createWorkflowTools,
  createMetaTools,
  createTextAnalyzeTools,
  createSnapshotTools,
  snapshotToolModule,
  createTodoTools,
  TodoRunStore,
  TodoRunStoreError,
  ok,
  fail,
  requireString,
  requireNumber,
  requireStringArray,
  requireText,
  requireBoolean,
  ToolCatalog,
  entityMutatingToolNames,
  canvasSyncMutatingToolNames,
  createProviderTools,
  type AgentTool,
  type ToolResult,
  type ToolModule,
  type AgentContext,
  type AgentOptions,
  type AgentExecutionOptions,
  type AgentLLMRequestDiagnostics,
  type AgentPersistentContextProjection,
  type AgentStreamEvent,
  type HistoryEntry,
  type StampedStreamEvent,
  type StreamEmit,
  type OrchestratorFactoryInput,
  type OrchestratorVariant,
  type CanvasLookup,
  type RunIntent,
  type CompletionContract,
  type CompletionEvidence,
  type ExitDecision,
  type BlockerReason,
  type ReadonlyCompletionEvidenceList,
  type CommitRequirement,
  type SuccessSignal,
  type ExitOutcomeKind,
  type ProcessPromptSpec,
  type ProcessPromptLifecycle,
  type ActivationContext,
  type ProcessPromptEvaluationResult,
  type ToolSelectionInput,
  type RunContext,
  type Scratchpad,
  type AllToolDeps,
  type CanvasToolDeps,
  type EntityToolDeps,
  type ScriptToolDeps,
  type JobToolDeps,
  type SeriesToolDeps,
  type SeriesEpisode,
  type ColorStyleToolDeps,
  type ProviderToolDeps,
  type ProviderInfo,
  type AssetToolDeps,
  type PromptToolDeps,
  type PromptDetail,
  type PromptListEntry,
  type RenderToolDeps,
  type PresetToolDeps,
  type WorkflowToolDeps,
  type CreateVisualAuditionsInput,
  type CreateVisualAuditionsResult,
  type ProduceWorkflowMediaInput,
  type PromptGuide,
  type MetaToolDeps,
  type CopywritingToolDeps,
  type VisionToolDeps,
  type TextAnalyzeToolDeps,
  type SnapshotToolDeps,
  type TodoSnapshot,
  type TodoItem,
  type TodoStatus,
  type TodoRunStoreOptions,
  type TodoSetInput,
  type TodoUpdateInput,
  type AppToolCatalog,
  type AppToolKey,
  type AppProcessCategory,
  type WorkflowToolPolicy,
  type WorkflowToolPolicyPhase,
} from '@lucid-fin/agent';

// Own exports (retained in this package)
export { JobQueue } from './job-queue.js';
export { LRUCache, type LRUCacheOptions } from './lru-cache.js';
export {
  compilePrompt,
  getCameraShot,
  type CameraShot,
  type CompiledPrompt,
  type PromptCompilerInput,
  type PromptMode,
  type ResolvedCharacter,
} from './prompt-compiler.js';
export { TemplateManager, type SceneTemplate } from './template-manager.js';
export {
  getToolCompactionCategory,
  getClassifiedToolNames,
  type ToolCompactionCategory,
} from '@lucid-fin/shared-utils';
